Repository FromDoppler/doppler-webapp, pull requests merged in 2021-09, with the labels that each got.

#1600 DW-1116-fix-form-upgrade-endpoint
  src/services/doppler-legacy-client.ts
Labels: size/XS

#1598 DW-1119 linkedin tag
  package.json
  src/components/ChangePlan/Checkout/CheckoutSummary.js
  src/components/Login/Login.js
  src/components/Signup/Signup.js
  src/hooks/useLinkedingInsightTag/index.js
  yarn.lock
Labels: size/M

#1578 DW-1044-perform-test-forms
  src/components/DopplerPlus/AgenciesForm.test.js
  src/components/DopplerPlus/ExclusiveForm.js
  src/components/DopplerPlus/ExclusiveForm.test.js
  src/components/DopplerPlus/UpgradeSuggestionForm.js
  src/components/DopplerPlus/UpgradeSuggestionForm.test.js
Labels: size/L

#1599 refactor: move buy link to up in header menu
  src/components/Header/HeaderUserMenu/HeaderUserMenu.js
  src/components/Header/HeaderUserMenu/HeaderUserMenu.test.js
Labels: size/M

#1597 refactor: update excluded list content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1596 Dw 1101 change promotional gif of contact policy
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/contact-policy-preview.gif
Labels: size/M

#1601 feat(bigquery): implement templates layouts with real content
  src/components/Integrations/BigQuery/AuthorizationPage.js
  src/components/Integrations/BigQuery/AuthorizationPage.test.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.test.js
  src/components/Integrations/BigQuery/bigquery_logo.png
  src/components/Integrations/BigQuery/google-data-studio.gif
  src/components/Integrations/BigQuery/styles/bigquery_logo.png
  src/components/shared/Promotional/Promotional.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-user-api-client.double.ts
Labels: size/L

#1611 feat: add guide lines to README.md
  README.md
Labels: size/L

#1612 fix(BannerUpgrade): fix object links
  src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.js
  src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js
Labels: size/S

#1614 fix(HeaderUserMenu): fix upgrade link when the user has a prepaid plan
  src/components/Header/HeaderUserMenu/HeaderUserMenu.js
  src/components/Header/HeaderUserMenu/HeaderUserMenu.test.js
Labels: size/M

#1610 feat(ControlPanel) : Add new component
  src/App.js
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanel.test.js
Labels: size/M

#1615 DW-1134-fix-monthly-deliveries-plan-tabs
  src/services/plan-service.test.js
  src/services/plan-service.ts
Labels: size/XS

#1616 DW-1147-redirect-submit-button-agencies-form
  src/components/DopplerPlus/AgenciesForm.js
  src/components/DopplerPlus/AgenciesForm.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1617 DW-1141: fix(PlanCalculator): for monthly plans there shouldn't be discounts
  src/doppler-types.ts
  src/services/doppler-legacy-client.test.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#1618 fix(breadcrumbs): Fix breadcrumb form links
  src/components/DopplerPlus/AgenciesForm.js
  src/components/DopplerPlus/AgenciesForm.test.js
  src/components/DopplerPlus/ExclusiveForm.js
  src/components/DopplerPlus/ExclusiveForm.test.js
  src/components/DopplerPlus/UpgradeSuggestionForm.js
  src/components/DopplerPlus/UpgradeSuggestionForm.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1619 [DAT-484] - Add edition view in the payment method section
  package.json
  src/components/ChangePlan/Checkout/Checkout.js
  src/components/ChangePlan/Checkout/Discounts/Discounts.js
  src/components/ChangePlan/Checkout/Discounts/Discounts.test.js
  src/components/ChangePlan/Checkout/PaymentMethod/CreditCard.js
  src/components/ChangePlan/Checkout/PaymentMethod/CreditCard.test.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/ChangePlan/Checkout/Step/Step.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/XXL

#1620 DW-1149-Fix-doppler-plus-forms-content
  src/components/DopplerPlus/UpgradeSuggestionForm.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1626 feat(plans): add currentSubscription filtering
  src/components/ChangePlan/ChangePlan.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.test.js
  src/doppler-types.ts
  src/services/plan-service.test.js
  src/services/plan-service.ts
Labels: size/M

#1627 DW-1148-cost-per-email-credits-plan
  src/components/ChangePlan/Checkout/PaymentMethod/CreditCard.test.js
  src/components/ChangePlan/PlanCalculator/PlanAgreement/PlanAgreement.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.test.js
  src/services/doppler-legacy-client.ts
Labels: size/S

#1628 refactor: fix spinner on reports page
  src/components/Reports/Reports.js
  src/components/Reports/Reports.test.js
  src/components/Reports/ReportsBox/ReportsBox.js
  src/components/Reports/ReportsBox/ReportsBox.test.js
  src/components/Reports/ReportsDailyVisits/ReportsDailyVisits.js
  src/components/Reports/ReportsFilters/ReportsFilters.js
  src/components/Reports/ReportsFilters/ReportsFilters.test.js
  src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.js
  src/components/Reports/ReportsTrafficSources/ReportsTrafficSources.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/datahub-client.doubles.ts
Labels: size/L

#1630 feat: filter plans by contacts for users with a prepaid account
  src/components/ChangePlan/PlanCalculator/PlanCalculator.js
  src/doppler-types.ts
  src/services/doppler-legacy-client.ts
  src/services/plan-service.test.js
  src/services/plan-service.ts
Labels: size/M

#1637 fix: fix error in plan selection view
  src/components/ChangePlan/ChangePlan.js
Labels: size/XS

#1631 fix(CloudTags): temporarily remove dp-recently-add class
  src/components/CloudTags/index.js
  src/components/CloudTags/index.test.js
Labels: size/XS

#1629 DW-1155-top-of-subscriber-plan
  src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.js
  src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1632 DW-1159-exclusive-clients
  src/components/ChangePlan/ChangePlan.js
  src/components/ChangePlan/ChangePlan.test.js
Labels: size/M

#1640 chore(bigquery): remove notification messages for demo in production
  src/components/Integrations/BigQuery/AuthorizationPage.js
  yarn.lock
Labels: size/M

#1646 DW-1121: fix(SiteTrackingRequired): Remove intermediate screen
  src/components/SiteTrackingRequired/SiteTrackingRequired.js
  src/components/SiteTrackingRequired/SiteTrackingRequired.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M
