Repository FromDoppler/doppler-webapp, pull requests merged in 2021-12, with the labels that each got.

#1768 [DAT-588] - Add 'Promocode' component
  .env
  src/components/ChangePlanDeprecated/Checkout/Checkout.js
  src/components/ChangePlanDeprecated/Checkout/Checkout.test.js
  src/components/ChangePlanDeprecated/Checkout/Discounts/Discounts.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/Promocode.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/Promocode.test.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.test.ts
  src/services/doppler-account-plans-api-client.ts
Labels: size/XL

#1771 chore(checkout): Move 'Checkout' folders into 'Plans' folder
  src/App.js
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/Plans/Checkout/BillingInformation/BillingInformation.test.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/Checkout.test.js
  src/components/Plans/Checkout/CheckoutSummary.js
  src/components/Plans/Checkout/ContactInformation/ContactInformation.js
  src/components/Plans/Checkout/ContactInformation/ContactInformation.test.js
  src/components/Plans/Checkout/Discounts/Discounts.js
  src/components/Plans/Checkout/Discounts/Discounts.styles.js
  src/components/Plans/Checkout/Discounts/Discounts.test.js
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
  src/components/Plans/Checkout/PaymentMethod/CreditCard.test.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/Plans/Checkout/PaymentMethod/Transfer.js
  src/components/Plans/Checkout/PaymentMethod/Transfer.test.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients.test.js
  src/components/Plans/Checkout/PurchaseSummary/Promocode.js
  src/components/Plans/Checkout/PurchaseSummary/Promocode.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/components/Plans/Checkout/Step/Step.js
  src/components/Plans/Checkout/Step/Step.test.js
Labels: size/XS

#1772 feat(checkout): Change "tooltip" and use "Info message"
  src/components/Plans/Checkout/Discounts/Discounts.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js
Labels: size/M

#1774 feat(checkout): Change style class for the considerations section
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
Labels: size/XS

#1775 [DAT-707] - Update texts for the 'extra credits'
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1777 fix: fix checkout url in plan calculator
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
Labels: size/S

#1773 Dw 1322 apply first steps in dashboard
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/components/Dashboard/FirstSteps/Notification/index.js
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/FirstSteps/index.test.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1776 [DOI-360] Add new method in dopplerUserApiClient service to get integrations status
  src/doppler-types.ts
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.test.ts
  src/services/doppler-user-api-client.ts
Labels: size/L

#1778 feat: add LearnWithDoppler component
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/LearnWithDoppler/Carousel/Carousel.js
  src/components/Dashboard/LearnWithDoppler/Carousel/Carousel.test.js
  src/components/Dashboard/LearnWithDoppler/Carousel/Slide/Slide.js
  src/components/Dashboard/LearnWithDoppler/Carousel/Slide/Slide.test.js
  src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js
  src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.test.js
  src/components/Dashboard/LearnWithDoppler/index.js
  src/components/Dashboard/LearnWithDoppler/index.test.js
Labels: size/L

#1783 Dw 1327 refactor my campaigns and my contacts
  src/components/Dashboard/CampaignSummary/index.js
  src/components/Dashboard/CampaignSummary/index.test.js
  src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.js
  src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.test.js
  src/components/Dashboard/ContactSummary/index.js
  src/components/Dashboard/ContactSummary/index.test.js
  src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.js
  src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.test.js
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.test.js
  src/components/Dashboard/Kpis/Kpi.js
  src/components/Dashboard/Kpis/Kpi.test.js
  src/components/Dashboard/LearnWithDoppler/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XL

#1780 [DOI-360] Display integrations connection status in control panel
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/reducers/controlPanelSectionsReducer.js
  src/components/ControlPanel/reducers/controlPanelSectionsReducer.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
  src/utils.test.js
  src/utils.ts
Labels: size/L

#1784 Dw 1052 add campaign report service
  .env.int
  .env.production
  .env.qa
  src/components/Dashboard/CampaignSummary/index.js
  src/components/Dashboard/CampaignSummary/index.test.js
  src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.js
  src/components/Dashboard/CampaignSummary/reducers/campaignSummaryReducer.test.js
  src/components/Dashboard/Dashboard.test.js
  src/index.js
  src/services/campaignSummary.test.ts
  src/services/campaignSummary.ts
  src/services/pure-di.tsx
  src/services/reports/index.double.ts
  src/services/reports/index.test.ts
  src/services/reports/index.ts
Labels: size/L

#1786 Dw 1057 add contact report service
  src/components/Dashboard/ContactSummary/index.js
  src/components/Dashboard/ContactSummary/index.test.js
  src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.js
  src/components/Dashboard/ContactSummary/reducers/contactSummaryReducer.test.js
  src/components/Dashboard/Dashboard.test.js
  src/services/contactSummary.test.ts
  src/services/contactSummary.ts
  src/services/pure-di.tsx
  src/services/reports/index.double.ts
  src/services/reports/index.test.ts
  src/services/reports/index.ts
Labels: size/L

#1788 Dw 1056 add overlay
  src/components/Dashboard/CampaignSummary/index.js
  src/components/Dashboard/CampaignSummary/index.test.js
  src/components/Dashboard/Kpis/KpiGroup.js
  src/components/Dashboard/Kpis/KpiGroup.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1787 Dw 1330 add link to first steps cards
  .env
  src/components/Dashboard/Dashboard.test.js
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1789 feat: add overlay to contact summary section
  src/components/Dashboard/ContactSummary/index.js
  src/components/Dashboard/ContactSummary/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1779 DW-1294-System-usage-summary-service
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/FirstSteps/index.test.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.test.js
  src/services/dashboardService/SystemUsageSummary.double.ts
  src/services/dashboardService/SystemUsageSummary.ts
  src/services/pure-di.tsx
Labels: size/L

#1792 feat: add final dashboard contents
  .env
  src/components/Dashboard/CampaignSummary/index.js
  src/components/Dashboard/ContactSummary/index.js
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Kpis/KpiGroup.js
  src/components/Dashboard/Kpis/KpiGroup.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1794 [DOI-379] Add MercadoLibre icon into ControlPanel
  src/components/ControlPanel/images/mercadolibre_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#1798 feat(checkout): Use useQueryParams hooks to get the parameters
  src/components/Plans/Checkout/CheckoutSummary.js
Labels: size/S

#1799 fix: fix date in campaign and contact services
  src/services/campaignSummary.ts
  src/services/contactSummary.ts
  src/services/reports/index.test.ts
Labels: size/S

#1791 feat(checkout): Add 'checkout summary' page
  src/components/Plans/Checkout/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.js
  src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/XL

#1800 [DAT-716] - Add 'back' button in the checkout page
  src/components/Plans/Checkout/Checkout.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1795 dashboard-as-default-page [TO BE PROOVED IN QA ENVIROMENT ]
  src/App.js
  src/components/SafeRedirect.js
  src/components/SafeRedirect.test.js
Labels: size/S

#1801 [DAT-721] - Missing translations for the placeholder
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1803 DW-1331-enviroment-vars-default-redirect
  .env.demo
  .env.development
  .env.int
  .env.production
  .env.qa
  src/App.js
  src/components/SafeRedirect.js
Labels: size/M

#1796 [No ticket] Modify integration status response mapping to be dynamic.
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.ts
Labels: size/S

#1804 [DAT-723] - Refresh page when the buy was succeed
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/S

#1806 [DAT-724] - Include the promocode in the purchase endpoint
  src/services/doppler-billing-user-api-client.ts
Labels: size/XS

#1807 feat: add calculate open rate
  src/services/campaignSummary.test.ts
  src/services/campaignSummary.ts
  src/services/reports/index.double.ts
  src/services/reports/index.ts
Labels: size/M

#1808 fix: fix contacts summary url
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1805 DW-1331-set-to-true-enviroment-prod-var [⚠️ DO NOT MERGE UNTIL RELEASE 23.6⚠️ ]
  .env.production
  src/components/Header/Header.js
Labels: size/XS

#1811 fix: first fix #, then check newdashboard
  src/App.js
Labels: size/XS

#1812 fix: fix demo day link
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1813 [DAT-726] - pass 'extraCredits' instead of 'promo-code' as parameter to the 'CheckoutSummary' page
  src/components/Plans/Checkout/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.js
  src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.test.js
Labels: size/M

#1814 fix: fix decimals
  src/services/campaignSummary.ts
Labels: size/XS

#1815 [DAT-728] - Include the 'origin_inbound' parameter in the buy of the plan
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/services/doppler-billing-user-api-client.ts
Labels: size/XS

#1816 feat: allow to redirect to external webapps in the same domain
  src/utils.ts
Labels: size/XS
