Repository FromDoppler/doppler-webapp, pull requests merged in 2021-07, with the labels that each got.

#1444 chore: add utm_content property to CreateUser
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/services/doppler-legacy-client.ts
Labels: size/M

#1457 feat(NavigatorTabs): implement tooltip component
  src/components/ChangePlan/PlanCalculator/NavigatorTabs/NavigatorTabs.js
Labels: size/S

#1454 feat(deploy): add dopplerci configuration
  .doppler-ci
Labels: size/XS

#1456 feat: add function to update account settings and tests
  src/services/doppler-contact-policy-api-client.double.ts
  src/services/doppler-contact-policy-api-client.test.ts
  src/services/doppler-contact-policy-api-client.ts
Labels: size/L

#1459 fix(Jenkinsfile): tag name was empty so now we use the function that …
  Jenkinsfile
Labels: size/XS

#1455 DW-992-allow-plan-upgrade
  src/components/ChangePlan/ChangePlan.js
  src/components/ChangePlan/ChangePlan.test.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
  src/services/plan-service.test.js
  src/services/plan-service.ts
Labels: size/M

#1462 feat(BannerUpgrade): add tests
  src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.js
  src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js
Labels: size/L

#1461 feat: add experimental feature
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
Labels: size/L

#1468 fix(utm): remove utms from url
  src/i18n/en.js
Labels: size/XS

#1470 fix: replace switch component by a form field
  src/components/ContactPolicy/ContactPolicy.js
  src/components/form-helpers/form-helpers.js
  src/components/shared/Switch/Switch.js
  src/components/shared/Switch/Switch.test.js
Labels: size/L

#1469 DW-977-change-ui-when-highest-plan-is-selected
  src/components/ChangePlan/PlanCalculator/BannerUpgrade/BannerUpgrade.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.test.js
  src/components/shared/Slider/Slider.js
  src/components/shared/Slider/Slider.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1467 Feature/dbd 10 big query authorization form
  src/App.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.test.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1478 fix: fix test exclusive and agencies form components
  src/components/DopplerPlus/AgenciesForm.test.js
  src/components/DopplerPlus/ExclusiveForm.test.js
Labels: size/S

#1466 feat: creation of the checkout process page with the Contact Informat…
  src/App.js
  src/components/ChangePlan/Checkout/Checkout.js
  src/components/ChangePlan/Checkout/Checkout.test.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlan/Checkout/Step/Step.js
  src/components/ChangePlan/Checkout/Step/Step.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/index.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.test.ts
  src/services/doppler-user-api-client.ts
  src/services/pure-di.tsx
  src/utils.ts
Labels: size/XXL

#1471 feat: integrate contact policy api
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/index.js
  src/services/doppler-contact-policy-api-client.double.ts
  src/services/doppler-contact-policy-api-client.ts
  src/services/pure-di.tsx
Labels: size/L

#1480 feat(big-query): add bigquery client and getEmailsData method
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.test.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.test.js
  src/index.js
  src/services/big-query-client.double.ts
  src/services/big-query-client.test.ts
  src/services/big-query-client.ts
  src/services/http-base-client.ts
  src/services/pure-di.tsx
Labels: javascript

#1502 [DAT-495] - Change input type for the "Industry" field to use "Select"
  .env
  .env.development
  src/components/ChangePlan/Checkout/Checkout.js
  src/components/ChangePlan/Checkout/Checkout.test.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlan/Checkout/Step/Step.test.js
  src/index.js
  src/services/pure-di.tsx
  src/services/static-data-client.double.ts
  src/services/static-data-client.test.ts
  src/services/static-data-client.ts
Labels: size/L

#1472 Dw 1014 add cloud tag field
  src/components/CloudTags/index.js
  src/components/CloudTags/index.test.js
  src/components/form-helpers/CloudTagField/index.js
  src/components/form-helpers/CloudTagField/index.test.js
  src/hooks/useCloudTags/index.js
  src/hooks/useCloudTags/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XL

#1505 DW-976-Add-email-cost
  src/components/ChangePlan/PlanCalculator/PlanAgreement/PlanAgreement.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1507 fix: move some unit tests from Checkout.test to ContactInformation.test
  src/components/ChangePlan/Checkout/Checkout.test.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js
Labels: size/XL

#1506 feat: show alert to confirm go back if there are unsaved changes
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1509 refactor: add tag cloud component to big query
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.test.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js
  src/components/form-helpers/CloudTagField/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/big-query-client.double.ts
Labels: size/L

#1510 feat: show success message and remove it after 3 seconds
  src/components/ContactPolicy/ContactPolicy.js
  src/components/shared/ShowLikeFlash/ShowLikeFlash.js
  src/components/shared/ShowLikeFlash/ShowLikeFlash.test.js
  src/utils.ts
Labels: size/M

#1517 [DAT-496] - Change the "Province/State" field to use "Select"
  src/components/ChangePlan/Checkout/Checkout.test.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js
  src/components/ChangePlan/Checkout/Step/Step.test.js
  src/services/doppler-user-api-client.double.ts
  src/services/static-data-client.double.ts
  src/services/static-data-client.test.ts
  src/services/static-data-client.ts
Labels: size/L

#1516 feat: [DAT-488] Upgrade plan form - Add confirmation message
  .env
  src/components/UpgradePlanForm/ConfirmationMessage.js
  src/components/UpgradePlanForm/ConfirmationMessage.test.js
  src/components/UpgradePlanForm/UpgradePlanForm.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1520 feat: add CloudTagList component and support for object array manipul…
  src/components/CloudTags/index.test.js
  src/components/form-helpers/CloudTagCompoundField/index.js
  src/components/form-helpers/CloudTagCompoundField/index.test.js
  src/hooks/useCloudTags/index.js
  src/hooks/useCloudTags/index.test.js
Labels: size/L

#1494 feat(BigQuery): add saveEmailsData to big query http client
  src/services/big-query-client.double.ts
  src/services/big-query-client.ts
Labels: size/S

#1519 feat: integrate user permissions api
  .env.qa
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/ContactPolicy/Promotional.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.test.ts
  src/services/doppler-user-api-client.ts
Labels: size/L

#1521 fix: [DAT-516] Fix button text of upgrade popup
  src/components/UpgradePlanForm/UpgradePlanForm.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1518 [DAT-507] - Integrate with the update endpoint
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.test.ts
  src/services/doppler-user-api-client.ts
Labels: size/L

#1522 feat: add cloud tag compound field integration to contact policy
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-contact-policy-api-client.double.ts
Labels: size/L

#1504 fix: improve tests
  package.json
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/Loading/Loading.js
  src/components/shared/ShowLikeFlash/ShowLikeFlash.test.js
  yarn.lock
Labels: size/XL
