Repository FromDoppler/doppler-webapp, pull requests merged in 2021-04, with the labels that each got.

#1333 feat: show the last 10 records of the permission history.
  .gitignore
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
  src/components/Reports/GDPRPermissions/SubscriberGdpr.styles.js
  src/components/Reports/GDPRPermissions/SubscriberGdprPermissions.js
  src/services/doppler-api-client.double.ts
Labels: size/L

#1340 Readme modify
  README.md
Labels: size/M

#1339 feat(Signup): add utms
  src/App.test.js
  src/components/Signup/Signup.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#1341 fix(style): fix gdpr history styles
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1353 chore: delete an unnecessary console log
  src/services/doppler-api-client.ts
Labels: size/XS
