Repository FromDoppler/doppler-webapp, pull requests merged in 2021-05, with the labels that each got.

#1358 fix: exclude the 'consent' field in the permission list
  src/components/Reports/GDPRPermissions/SubscriberGdprPermissions.js
Labels: size/XS

#1372 feat: show the arrow button if the value of the field is none
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
Labels: size/M

#1374 feat: enable feature to all users
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
Labels: size/L

#1381 fix: display an error message when a response error is received
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
Labels: size/M

#1383 fix: show consent without response when receiving null permission value
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/services/doppler-api-client.double.ts
  src/services/doppler-api-client.ts
Labels: size/S

#1384 fix(Signup): send last 10 items in utm cookies
  src/components/Signup/Signup.js
Labels: size/XS

#1382 feat: add a link at the bottom of the report to download the permission history
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
  src/components/Reports/GDPRPermissions/SubscriberGdpr.styles.js
  src/components/Reports/GDPRPermissions/SubscriberGdprPermissions.js
  src/components/Reports/GDPRPermissions/SubscriberGdprPermissions.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-api-client.double.ts
  src/services/doppler-api-client.test.ts
  src/services/doppler-api-client.ts
Labels: size/L

#1391 feat: add modification source column
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1397 chore(lang): update translations
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS
