Repository FromDoppler/doppler-webapp, pull requests merged in 2021-11, with the labels that each got.

#1690 [DAT-600] - Include AR transfer in the payment method section
  src/components/ChangePlanDeprecated/Checkout/BillingInformation/BillingInformation.js
  src/components/ChangePlanDeprecated/Checkout/Checkout.js
  src/components/ChangePlanDeprecated/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlanDeprecated/Checkout/Discounts/Discounts.js
  src/components/ChangePlanDeprecated/Checkout/Discounts/Discounts.test.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/Transfer.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/Transfer.test.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
  src/services/static-data-client.double.ts
  src/services/static-data-client.ts
  src/validations.ts
Labels: size/XXL

#1701 Dw 1235 update new plan calculator urls
  src/App.js
  src/components/NewFeatures/NewFeatures.js
  src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.js
  src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.test.js
  src/doppler-types.ts
Labels: size/M

#1695 [DOI-309] Add native integrations into control panel
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanel.test.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.styles.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.test.js
  src/components/ControlPanel/images/Tiendanube_icon.svg
  src/components/ControlPanel/images/Typeform_icon.png
  src/components/ControlPanel/images/Unbounce_icon.svg
  src/components/ControlPanel/images/bigquery_icon.png
  src/components/ControlPanel/images/bmw_crm_icon.png
  src/components/ControlPanel/images/easycommerce_icon.svg
  src/components/ControlPanel/images/google_analitics_icon.png
  src/components/ControlPanel/images/magento_icon.png
  src/components/ControlPanel/images/prestashop_icon.png
  src/components/ControlPanel/images/shopify_icon.png
  src/components/ControlPanel/images/tokko_icon.png
  src/components/ControlPanel/images/vtex_icon.svg
  src/components/ControlPanel/images/woocommerce_icon.png
  src/components/ControlPanel/images/zoho_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.test.ts
  src/services/control-panel-service.ts
Labels: size/L

#1704 [DAT-668]- Replace STANDARD by PREMIUM
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1703 Dw 1253 create slider component
  src/components/Plans/PlanCalculator/Slider/index.js
  src/components/Plans/PlanCalculator/Slider/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.styles.js
  src/components/Plans/PlanCalculator/index.test.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js
  src/components/shared/Slider/Slider.js
  src/components/shared/Slider/Slider.test.js
  src/utils.test.js
  src/utils.ts
Labels: size/XL

#1705 DW-1252-Banner-update-component
  src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.js
  src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.test.js
  src/components/Plans/PlanCalculator/BannerUpgrade/getUpgradeInfo.js
Labels: size/L

#1707 Dw 1256 create back and buy buttons
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.styles.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.styles.js
  src/components/Plans/PlanCalculator/index.test.js
  src/hooks/useQueryParams/index.js
Labels: size/L

#1706 [No-ticket] Add advanced preferences content
  src/components/ControlPanel/images/custom_domain_icon.png
  src/components/ControlPanel/images/domain_key_icon.png
  src/components/ControlPanel/images/doppler_api_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/M

#1700 fix: error on test
  src/components/Integrations/BigQuery/AuthorizationPage.js
Labels: size/S

#1711 [DAT-675] - The free user cannot select payment method
  src/components/ChangePlanDeprecated/Checkout/Checkout.js
  src/components/ChangePlanDeprecated/Checkout/Discounts/Discounts.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/Transfer.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/M

#1710 feat: [DAT-598] Integrate with POST agreement service
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#1713 Dw 1259 add is visible property to slider component
  src/components/Plans/PlanCalculator/Slider/index.js
  src/components/Plans/PlanCalculator/Slider/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.test.js
Labels: size/L

#1714 DW-1254-Price-per-month-component
  src/components/Plans/PlanCalculator/NavigatorTabs/PlanPrice/PlanPricePerMonth.js
  src/components/Plans/PlanCalculator/NavigatorTabs/PlanPrice/PlanPricePerMonth.test.js
Labels: size/M

#1712 Dw 1258 aplly banner upgrade component to plan calculator
  src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.test.js
Labels: size/M

#1716 feat(checkout): Add purchuse legend when the buy is by credits
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1717 [DAT-678] - Remove the harcoded values and use the values declared in doppler-types.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/S

#1718 feat(checkout): Apply background styles regarding UI library
  src/components/ChangePlanDeprecated/Checkout/Checkout.js
Labels: size/L

#1715 chore: added Origin_Inbound parameter
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/services/doppler-legacy-client.ts
Labels: size/XS

#1708 feat(ControlPanel): Add connection status for integrations
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanel.styles.js
  src/components/ControlPanel/ControlPanel.test.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.styles.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.test.js
  src/components/ControlPanel/images/connected.png
  src/components/ControlPanel/images/connection_alert.png
  src/components/ControlPanel/images/disconnected.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/L

#1720 feat(checkout): hide message "Proxima factura" and "Meses a abonar" w…
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js
Labels: size/L

#1721 Dw 1255 create discount component
  src/components/Plans/PlanCalculator/Discounts/index.js
  src/components/Plans/PlanCalculator/Discounts/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js
  src/doppler-types.ts
Labels: size/L

#1724 [DAT-686] - Update discount legends in the discount component
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1725 fix (checkout): When the user changes the country the state was left with the previous value
  src/components/ChangePlanDeprecated/Checkout/BillingInformation/BillingInformation.js
Labels: size/XS

#1719 DW-1241-Add-signUp-content
  src/components/Signup/Signup.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1723 [DAT-684] - Show or hide payment method options depending of billing country
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.test.js
Labels: size/L

#1726 Dw 1265 create plan price
  src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/index.js
  src/components/Plans/PlanCalculator/PlanPrice/index.test.js
Labels: size/L

#1727 DW-1262-PriceWithoutDiscount-component
  src/components/Plans/PlanPrice/PlanPriceWithoutDiscounts.js
  src/components/Plans/PlanPrice/PlanPriceWithoutDiscounts.test.js
Labels: size/M

#1730 Revert-content-signup-changes
  src/components/Signup/Signup.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1729 Dw 1266 apply plan price to plan calculator
  src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithoutDiscount/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithoutDiscount/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/index.js
  src/components/Plans/PlanCalculator/PlanPrice/index.test.js
  src/components/Plans/PlanCalculator/index.js
Labels: size/M

#1728 [DAT-688] - When the user does not have any type of payment the tr…
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/PaymentMethod.js
Labels: size/S

#1732 feat: add redirect from /plan-selection to /plan-selection/premium/by…
  src/App.js
  src/App.test.js
Labels: size/M

#1733 [DAT-689] - Add available credit cards legend when the credit card section is in update view
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/CreditCard.js
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/CreditCard.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1735 [DAT-690] - Integrate new changes from UI library
  .env
  src/components/ChangePlanDeprecated/Checkout/Step/Step.js
Labels: size/XS

#1734 feat: [DAT-555] Add experimental feature "newCheckoutEnabled" for the new checkout
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/M

#1737 DW-1241-Sticky-helloBar
  .env
  src/components/Header/Header.js
  src/components/Header/HeaderMessages/HeaderMessages.js
Labels: size/XS

#1738 feat: add query params when the user navigates between tabs
  src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.js
  src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.test.js
Labels: size/M

#1736 [DOI-350] Modify control panel styles
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.styles.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#1740 fix: fix redirect to create a new list
  .env
  src/components/SubscriberListSelector/SubscriberListSelector.js
Labels: size/XS

#1741 fix(checkout): Remove warning test
  src/components/ChangePlanDeprecated/Checkout/PaymentMethod/CreditCard.test.js
Labels: size/XS

#1742 fix: enable button of contact policy when a list is deleted
  src/components/ContactPolicy/ContactPolicy.js
Labels: size/XS

#1743 feat: add PromoCode to PlanCalculator
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/XS

#1739 [DOI-310] Add zapier integrations
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.test.js
  src/components/ControlPanel/images/eventbrite_icon.png
  src/components/ControlPanel/images/facebook_lead_ads_icon.png
  src/components/ControlPanel/images/go_to_webinar_icon.png
  src/components/ControlPanel/images/hubspot_icon.png
  src/components/ControlPanel/images/optin_monster_icon.png
  src/components/ControlPanel/images/salesforce_icon.png
  src/components/ControlPanel/images/zapier_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.test.ts
  src/services/control-panel-service.ts
Labels: size/L

#1744 [DOI-311] Add external integrations
  src/components/ControlPanel/images/facebook_icon.png
  src/components/ControlPanel/images/infor_icon.png
  src/components/ControlPanel/images/lander__icon.png
  src/components/ControlPanel/images/learnpress_icon.png
  src/components/ControlPanel/images/payu_icon.png
  src/components/ControlPanel/images/sumaprop_icon.png
  src/components/ControlPanel/images/viewed_icon.png
  src/components/ControlPanel/images/wix_icon.png
  src/components/ControlPanel/images/wizell_icon.png
  src/components/ControlPanel/images/xintel_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/L

#1749 fix: fix space between amount & currency
  src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js
Labels: size/XS

#1750 fix: fix contend in plan calculator
  src/i18n/es.js
Labels: size/XS

#1751 fix: fix the order of discounts in the plan calculator
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js
Labels: size/S

#1731 ☢️⚠️ DO NOT MERGE BEFORE 2021-11-17 DOPPLER RELEASE - DW-1205-Add-Trial-signUp-content
  src/components/Signup/Signup.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1754 fix: create new tab with help information on click link
  src/components/Integrations/BigQuery/AuthorizationPage.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1756 feat: remove code analyzer
  .github/workflows/codeql-analysis.yml
Labels: size/M

#1755 DW-1296-fix-prepaid-planName
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1753 [DAT-622] - Update 'EditAddRecipients' component to supports add or edit.
  src/components/ChangePlanDeprecated/Checkout/Checkout.test.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/InvoiceRecipients.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/InvoiceRecipients.test.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlanDeprecated/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/L

#1757 [DOI-358] Disable control panel boxes for free users and hidde plans&specs box
  src/services/control-panel-service.test.ts
  src/services/control-panel-service.ts
Labels: size/M

#1760 fix: fix per month label for credits plan
  src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PricePerMonth/index.test.js
Labels: size/S

#1761 chore(ControlPanel): change wrong content
  src/i18n/en.js
Labels: size/XS

#1759 Dw 1291 create first steps
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/components/Dashboard/FirstSteps/ActionBox/index.test.js
  src/components/Dashboard/FirstSteps/Notification/index.js
  src/components/Dashboard/FirstSteps/Notification/index.test.js
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/FirstSteps/index.test.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1762 Refactoring PlanCalculator and plansByTypeReducer
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js
Labels: size/L

#1765 fix: replace shopify url on int a qa environment
  .env.int
  .env.qa
Labels: size/XS

#1766 [No-ticket] Fix some typos in control panel content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1764 feat: apply back information mapping
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/components/Dashboard/FirstSteps/ActionBox/index.test.js
  src/components/Dashboard/FirstSteps/Notification/index.js
  src/components/Dashboard/FirstSteps/Notification/index.test.js
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/FirstSteps/index.test.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1770 [DOI-373] Add subtitle description into Control Panel
  src/components/ControlPanel/ControlPanel.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#1767 DW-1290-get-previous-disccount
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js
Labels: size/L
