Repository FromDoppler/doppler-webapp, pull requests merged in 2021-08, with the labels that each got.

#1528 feat: add list exclusion configuration section
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1515 fix(chat): replace zoho chat with zendesk chat
  public/index.html
  public/zoho-chat.js
  src/App.js
  src/App.test.js
  src/components/Login/Login.js
  src/index.js
  src/utils.ts
Labels: size/L

#1523 Dw 1082 add husky and lint staged
  .lintstagedrc.js
  Dockerfile
  Dockerfile.BUILDS_AND_CDN
  Dockerfile.LOCAL
  Dockerfile.RELEASES
  Dockerfile.swarm
  package.json
  prepare.js
  yarn.lock
Labels: size/L

#1529 DW-1081-discount-message-when-higher-plans
  src/components/ChangePlan/PlanCalculator/Discounts/Discounts.js
  src/components/ChangePlan/PlanCalculator/Discounts/Discounts.styles.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.test.js
  src/headerData.json
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#1533 DW-1080-Fix-decimals
  src/components/ChangePlan/PlanCalculator/PlanAgreement/PlanAgreement.js
  src/utils.ts
Labels: size/XS

#1537 fix: [DAT-516] Fix text button for last plan form
  src/components/UpgradePlanForm/UpgradePlanForm.js
Labels: size/XS

#1543 feat: add promotional component
  .env
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/ContactPolicy/Promotional.js
  src/components/shared/Promotional/Promotional.js
  src/components/shared/Promotional/Promotional.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1535 feat: add list selection page component
  package.json
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/Modal/Modal.js
  src/components/SubscriberListSelector/SubscriberListSelector.js
  src/components/SubscriberListSelector/SubscriberListSelector.test.js
  src/hooks/useInfinitePaged/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-api-client.double.ts
  src/services/doppler-api-client.test.ts
  src/services/doppler-api-client.ts
  yarn.lock
Labels: size/L

#1544 feat: load pre-selected lists
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/SubscriberListSelector/SubscriberListSelector.js
  src/components/SubscriberListSelector/SubscriberListSelector.test.js
  src/components/shared/Promotional/Promotional.js
  src/services/doppler-api-client.double.ts
  src/services/doppler-contact-policy-api-client.double.ts
  src/services/doppler-contact-policy-api-client.test.ts
Labels: size/L

#1546 feat: show message when max number of lists is reached
  .env
  src/components/ContactPolicy/ContactPolicy.js
  src/components/Modal/Modal.js
  src/components/SubscriberListSelector/SubscriberListSelector.js
  src/components/SubscriberListSelector/SubscriberListSelector.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1536 [DAT-478] - Add "Billing Information" section into Checkout process
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/ChangePlan/Checkout/BillingInformation/BillingInformation.js
  src/components/ChangePlan/Checkout/BillingInformation/BillingInformation.test.js
  src/components/ChangePlan/Checkout/Checkout.js
  src/components/ChangePlan/Checkout/Step/Step.js
  src/i18n/en.js
  src/i18n/es.js
  src/index.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
  src/services/doppler-user-api-client.double.ts
  src/services/pure-di.tsx
Labels: size/XL

#1547 [DAT-525] - Update content for the 'contact information' section
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1548 feat: add styles and some fixes
  .env
  src/components/ContactPolicy/ContactPolicy.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.test.js
  src/components/SubscriberListSelector/SubscriberListSelector.js
  src/components/form-helpers/form-helpers.js
  src/components/shared/Promotional/Promotional.js
  src/utils.ts
Labels: size/L

#1550 feat: update excluded lists when confirm selection
  src/components/ContactPolicy/ContactPolicy.js
  src/components/SubscriberListSelector/SubscriberListSelector.js
  src/components/SubscriberListSelector/SubscriberListSelector.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1551 [DAT-539] - Removed the success message
  src/components/ChangePlan/Checkout/BillingInformation/BillingInformation.js
  src/components/ChangePlan/Checkout/BillingInformation/BillingInformation.test.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1561 feat(bigquery): implement get and save method for integration with API
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js
  src/services/big-query-client.ts
  src/services/pure-di.tsx
Labels: size/M

#1565 feat(bigquery): add bigquery pages to new features page
  src/components/NewFeatures/NewFeatures.js
Labels: size/S

#1563 feat: add security question to contact information
  src/components/ChangePlan/Checkout/Checkout.test.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.test.js
  src/components/ChangePlan/Checkout/Step/Step.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.ts
  src/services/static-data-client.double.ts
  src/services/static-data-client.ts
Labels: size/L

#1567 fix: remove warnings
  src/App.js
  src/components/ChangePlan/Checkout/BillingInformation/BillingInformation.js
  src/components/ChangePlan/Checkout/ContactInformation/ContactInformation.js
  src/components/ChangePlan/PlanCalculator/Discounts/Discounts.js
  src/components/ChangePlan/PlanCalculator/PlanCalculator.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationPage.js
  src/components/SubscriberListSelector/SubscriberListSelector.js
  src/components/shared/Promotional/Promotional.styles.js
  src/hooks/useInfinitePaged/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1566 feat(CI): add warning as errors in build
  .env
  src/validations.ts
Labels: size/XS

#1570 chore: add husky into gitignore
  .gitignore
Labels: size/XS

#1564 feat: add after remove callback (optional)
  src/components/CloudTags/index.js
  src/components/form-helpers/CloudTagCompoundField/index.js
  src/components/form-helpers/CloudTagCompoundField/index.test.js
Labels: size/M

#1552 feat: integrate no list component and error message
  src/components/ContactPolicy/ContactPolicy.js
  src/components/SubscriberListSelector/SubscriberListSelector.js
  src/components/SubscriberListSelector/SubscriberListSelector.test.js
  src/components/shared/ConfirmationBox/ConfirmationBox.js
  src/components/shared/ConfirmationBox/ConfirmationBox.styles.js
  src/components/shared/ConfirmationBox/ConfirmationBox.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-contact-policy-api-client.test.ts
  src/services/doppler-contact-policy-api-client.ts
Labels: size/L

#1568 [DAT-542] - Create "Payment Method" section (readonly view)
  package.json
  src/components/ChangePlan/Checkout/Checkout.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.styles.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/ChangePlan/PlanCalculator/Discounts/Discounts.js
  src/components/ContactPolicy/ContactPolicy.js
  src/headerData.json
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-billing-user-api-client.double.ts
Labels: size/L

#1571 feat: add code analyzer workflow
  .github/workflows/codeql-analysis.yml
Labels: size/M

#1584 feat(bigquery): add notification method to bigquery client and logic …
  src/components/Integrations/BigQuery/AuthorizationPage.js
  src/components/Integrations/BigQuery/AuthorizationPage.test.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.js
  src/components/Integrations/BigQuery/ControlPanel/AuthorizationForm.test.js
  src/services/big-query-client.double.ts
  src/services/big-query-client.ts
Labels: size/L

#1581 [DAT-542] - Integrate "Payment method" section with the APIs (account-plans and billing-user)
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/ChangePlan/Checkout/Checkout.js
  src/components/ChangePlan/Checkout/Checkout.test.js
  src/components/ChangePlan/Checkout/Discounts/Discounts.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.styles.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/index.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.test.ts
  src/services/doppler-account-plans-api-client.ts
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
  src/services/pure-di.tsx
Labels: size/XL

#1583 DW-498-Doppler-plus-content
  src/components/ChangePlan/ChangePlan.js
  src/components/ChangePlan/ChangePlan.test.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/FAQ/constants.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1593 feat: add test coverage for webapp.
  package.json
Labels: size/S
