Repository FromDoppler/doppler-webapp, pull requests merged in 2021-10, with the labels that each got.

#1641 feat(checkout): Add 'Purchase summary' section
  .env
  src/components/ChangePlan/Checkout/Checkout.js
  src/components/ChangePlan/Checkout/Checkout.test.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
  src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.test.ts
  src/services/doppler-account-plans-api-client.ts
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/XXL

#1639 DS-2618-Learn-with-doppler
  src/components/Dashboard/Carousel/Carousel.js
  src/components/Dashboard/Carousel/Carousel.test.js
  src/components/Dashboard/Carousel/Slide/Slide.js
  src/components/Dashboard/Carousel/Slide/Slide.test.js
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.styles.js
  src/components/Dashboard/Dashboard.test.js
  src/components/Dashboard/TextPreviewPost/TextPreviewPost.js
  src/components/Dashboard/TextPreviewPost/TextPreviewPost.test.js
Labels: size/L

#1648 fix(zoho-chat): remove zoho chat
  public/index.html
  public/zoho-chat.css
  public/zoho-chat.js
Labels: size/L

#1649 [DAT-618] - Add new legends to show the information about the invoice
  src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1647 fix: [DAT-597] Update PaymentMethod properties
  src/components/ChangePlan/Checkout/PaymentMethod/CreditCard.js
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#1654 [DAT-629] - Set placeholder for the 'Purchase Summary' section when the page is loading
  src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/ChangePlan/Checkout/PurchaseSummary/PurchaseSummary.test.js
Labels: size/M

#1653 DW-1192-New-feature
  src/components/NewFeatures/NewFeatures.js
Labels: size/S

#1656 chore: [DAT-631] Add idSelectedPlan property in PaymentMethod object
  src/components/ChangePlan/Checkout/PaymentMethod/PaymentMethod.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#1670 [DOI-313] Add basic sections into control panel
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanel.test.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.test.js
  src/components/ControlPanel/controlPanelSections.js
  src/components/ControlPanel/images/account_information_icon.png
  src/components/ControlPanel/images/account_movements_icon.png
  src/components/ControlPanel/images/auto_publish_icon.png
  src/components/ControlPanel/images/billing_information_icon.png
  src/components/ControlPanel/images/bounce_handling_icon.png
  src/components/ControlPanel/images/contact_information_icon.png
  src/components/ControlPanel/images/contact_policy_icon.svg
  src/components/ControlPanel/images/control_panel_icons.png
  src/components/ControlPanel/images/email_parameter_icon.png
  src/components/ControlPanel/images/footer_and_header_icon.png
  src/components/ControlPanel/images/plans_and_specs_icon.png
  src/components/ControlPanel/images/rss_preferences_icon.png
  src/components/ControlPanel/images/site_tracking_icon.png
  src/components/ControlPanel/images/sms_settings_icon.png
  src/components/ControlPanel/images/social_network_icon.png
  src/components/ControlPanel/images/subscribers_scoring_icon.png
  src/components/ControlPanel/images/unopened_mails_config_icon.png
  src/components/ControlPanel/images/unsubscription_link_icon.png
  src/components/ControlPanel/images/viralization_icon.png
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L
