Repository FromDoppler/doppler-webapp, pull requests merged in 2021-06, with the labels that each got.

#1373 DW-889: fix(utmCookies): add only one entrance for each navigation
  src/components/Signup/Signup.js
  src/services/pure-di.tsx
  src/services/utm-cookies-manager.js
  src/services/utm-cookies-manager.test.js
Labels: size/M

#1401 fix: add missing dependency to useEffect
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
Labels: size/M

#1402 DW-930 remove utms from login and signup
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1390 DW-926 add gclid parameter
  src/App.test.js
  src/components/Signup/Signup.js
  src/services/doppler-legacy-client.ts
  src/services/utm-cookies-manager.js
  src/services/utm-cookies-manager.test.js
Labels: size/L

#1403 feat: add Contact Policy component with breadcumb and intro text
  src/App.js
  src/components/ContactPolicy/ContactPolicy.js
  src/components/NewFeatures/NewFeatures.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1414 DW-937: Remove publish to docker in build-n-publish script.
  Dockerfile.RELEASES
Labels: size/S

#1417 feat(en,es): add text in reports
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1418 DW-947 alignment fix in gdpr tables
  .env
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.js
  src/components/Reports/GDPRPermissions/PermissionExpandableRow.test.js
  src/services/doppler-api-client.double.ts
Labels: size/S

#1423 feat: add switch to enable/disable the feature
  .env
  src/components/ContactPolicy/ContactPolicy.js
  src/components/shared/Switch/Switch.js
  src/components/shared/Switch/Switch.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1424 DW-963: fix(Notifications): allow more than one Notifications
  src/components/Header/Header.js
  src/components/Header/Notifications.js
  src/components/Header/Notifications.test.js
Labels: size/M

#1426 DW-957-remove-duplicate-zoho-css
  public/index.html
Labels: size/XS

#1425 Dw 948 fix duplicate emails
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/ForgotPassword.test.js
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
Labels: size/L

#1429 DE-184 Add UX Google Tag Manager
  public/index.html
Labels: size/S

#1428 fix(console): fix console test errors
  src/App.test.js
  src/components/DopplerPlus/ExclusiveForm.test.js
  src/components/ForgotPassword/ForgotPassword.test.js
  src/components/form-helpers/form-helpers.js
  src/hooks/useTimeout/index.js
  src/hooks/useTimeout/index.test.js
  src/services/doppler-legacy-client.doubles.ts
Labels: size/L

#1427 Dw 544 format numbers in plan calculator
  src/components/ChangePlan/ChangePlan.js
  src/components/ChangePlan/PlanCalculator.js
  src/components/ChangePlan/PlanCalculator.test.js
  src/components/shared/Slider/Slider.js
  src/utils.test.js
  src/utils.ts
Labels: size/M

#1437 fix(PlanCalculator): fix order of plans
  src/components/ChangePlan/PlanCalculator.test.js
  src/services/plan-service.ts
  src/utils.test.js
  src/utils.ts
Labels: size/L

#1431 fix: internal link with target _blank
  src/components/SiteTrackingRequired/SiteTrackingRequired.js
Labels: size/XS

#1439 feat: add contact policy api double
  src/services/doppler-contact-policy-api-client.double.ts
  src/services/doppler-contact-policy-api-client.test.ts
  src/services/doppler-contact-policy-api-client.ts
Labels: size/L

#1440 [DW-540] show decimals fix rounding
  src/components/ChangePlan/PlanCalculator.js
  src/components/ChangePlan/PlanCalculator.test.js
  src/utils.test.js
  src/utils.ts
Labels: size/M

#1438 test(Card): add test to Card, CardAction, CardPrice, Ribbon and CardF…
  src/components/ChangePlan/Card.js
  src/components/ChangePlan/Card.test.js
Labels: size/L

#1432 feat: add inputs and buttons
  .env
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1430 DW-973 fix(Promotions): get default image from be
  src/components/shared/Promotions/Promotions.js
  src/components/shared/Promotions/Promotions.test.js
Labels: size/S

#1442 DW-989-update-plan-agencies-content
  src/components/DopplerPlus/AgenciesForm.js
  src/components/DopplerPlus/AgenciesForm.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1441 [DW-991] apply transition UI in tabs
  src/components/ChangePlan/PlanCalculator.js
  src/components/ChangePlan/PlanCalculator.styles.js
Labels: size/S

#1449 fix(ForgotPassword): add dependency doppler sites client
  src/components/ForgotPassword/ForgotPassword.test.js
  src/components/Signup/Signup.test.js
Labels: size/XS

#1451 DW-980-show-tooltip-when-equal-plan-is-selected
  src/components/ChangePlan/PlanCalculator.js
  src/components/ChangePlan/PlanCalculator.styles.js
  src/components/TooltipContainer/TooltipContainer.js
  src/components/TooltipContainer/TooltipContainer.styles.js
  src/components/TooltipContainer/TooltipContainer.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/plan-service.ts
Labels: size/L

#1453 [DW-990] fix test
  src/components/shared/Slider/Slider.test.js
Labels: size/XS

#1452 test(ChangePlan): add test to change plan components
  src/components/ChangePlan/ChangePlan.js
  src/components/ChangePlan/ChangePlan.test.js
  src/services/doppler-legacy-client.doubles.ts
Labels: size/XL

#1443 feat(FAQ): add frecuently ask question section in plans section
  .env
  src/components/ChangePlan/ChangePlan.js
  src/components/FAQ/QAItem/index.js
  src/components/FAQ/QAItem/index.test.js
  src/components/FAQ/constants.js
  src/components/FAQ/index.js
  src/components/FAQ/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L
