Repository FromDoppler/doppler-webapp, pull requests merged in 2022-05, with the labels that each got.

#1963 [DAT-916] - Create endpoint to retrieve the document types from cdn
  src/services/static-data-client.double.ts
  src/services/static-data-client.test.ts
  src/services/static-data-client.ts
Labels: size/M

#1957 [DOI-505] Fix anchor links in control panel
  src/components/ControlPanel/ControlPanel.js
  src/hooks/useHashScrollHandler/index.js
Labels: size/S

#1964 Dat 609 add mercado pago to checkout
  src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js
  src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.test.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/validations.ts
Labels: size/XL

#1965 feat: add dni a transfer
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.test.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
Labels: size/S

#1966 feat: add mercadopago to map
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#1972 feat: add icon at mercado pago summary
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Labels: size/XS

#1977 [No-Ticket] Send document number as string when the payment method is transfer
  src/services/doppler-billing-user-api-client.ts
Labels: size/XS

#1974 fix: add images and change images reference
  public/images/approve-money.svg
  public/images/check-grey.svg
  public/images/checkout-success.svg
  public/images/create-mail.svg
  public/images/dollar-coin.svg
  public/images/icon-pcontacto.svg
  public/images/inbox.svg
  public/images/lists.svg
  public/images/login-en.png
  public/images/login-es.png
  public/images/mercado-pago.svg
  public/images/newfeature-icon.svg
  public/images/three-points.svg
  public/images/violet-yellow.png
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1978 [DAT-937] - Add content when the user is final consumer
  src/components/Plans/Checkout/CheckoutSummary/TransferInformation/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1973 DE-607 Replace ui library whit style guide in webapp
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  public/index.html
  src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.styles.js
  src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
  src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
Labels: size/M

#1981 [DAT-938] - Update mercadopago content
  src/i18n/es.js
Labels: size/XS

#1983 [DAT-920] - Integrate new checkout with argentinian user and free
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
Labels: size/L

#1987 [DOI-581] Update purchase intention in checkout
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/Checkout.test.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#1982 feat: deprecate ui library in webapp
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  public/index.html
  src/App.css
  src/components/Reports/ReportsHoursVisits/ReportsHoursVisits.styles.js
  src/components/Reports/ReportsPageRanking/ReportsPageRanking.js
  src/components/Reports/ReportsPageRanking/ReportsPageRanking.styles.js
Labels: size/M

#1991 [DAT-572] - Show an error when first data throws an exception
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1993 [No-Ticket] - Add more exception error from first data
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/doppler-types.ts
Labels: size/XS

#1992 [DAT-949] - Remove sorting in the industries
  src/components/Plans/Checkout/ContactInformation/ContactInformation.js
Labels: size/XS
