Repository FromDoppler/doppler-webapp, pull requests merged in 2022-03, with the labels that each got.

#1887 [DOI-476] Make mitienda icon visible in control panel
  src/services/control-panel-service.ts
Labels: size/XS

#1888 Remove sumaprop from control panel
  src/components/ControlPanel/images/sumaprop_icon.png
  src/services/control-panel-service.ts
Labels: size/XS

#1889 [DAT-814] - Integrate the buy the plan by emails for the final users
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/XS

#1893 feat: add spanish content for demoday
  src/i18n/es.js
Labels: size/XS

#1895 [DOI-472] Add anchor links for control panel sections
  src/components/ControlPanel/ControlPanel.js
  src/services/control-panel-service.ts
Labels: size/S

#1896 [DAT-602] - Integrate colombia transfer in the checkout process
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Colombia/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Colombia/index.test.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/L

#1902 feat: add support for plans by contacts
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.test.js
Labels: size/M

#1903 test: add test to plan calculator
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.test.js
Labels: size/L

#1882 chore: remove noreferrer attribute for doppler urls
  package.json
  src/components/ForgotPassword/ForgotPassword.js
  src/components/Login/Login.js
  src/components/Signup/Signup.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1905 [DAT-832] - Allow purchases plan by credits, emails or contacts for free users and that their country is not in AR/MX/CO
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/XS

#1894 chore: replace localstorage with cookie
  src/App.test.js
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/services/doppler-legacy-client.ts
  src/services/pure-di.tsx
  src/services/utm-cookies-manager.js
  src/services/utm-cookies-manager.test.js
Labels: size/L

#1908 feat: add typeform
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  package.json
  src/components/Dashboard/Dashboard.js
  src/components/TypeformSurvey/index.js
  src/components/TypeformSurvey/index.test.js
  src/components/TypeformSurvey/reducers/surveyReducer.js
  src/components/TypeformSurvey/reducers/surveyReducer.test.js
  src/services/pure-di.tsx
  src/services/surveyService/index.test.ts
  src/services/surveyService/index.ts
  yarn.lock
Labels: size/L

#1909 [No-Task] - Remove an unnecessary service call in the Transfer component
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
Labels: size/M

#1911 [DAT-854] - Add plan type in the checkout summary page
  src/components/Plans/Checkout/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1910 [DAT-851] - Update checkout summary page to support transfer with promocode of the 100% discount
  src/components/Plans/Checkout/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary.test.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
Labels: size/L

#1913 fix: avoid duplicating cookie entry on same session
  src/services/utm-cookies-manager.js
Labels: size/XS

#1914 Dat 841 add surve client to doppler legacy
  src/components/TypeformSurvey/index.js
  src/components/TypeformSurvey/index.test.js
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.ts
  src/services/pure-di.tsx
  src/services/surveyService/index.test.ts
  src/services/surveyService/index.ts
Labels: size/L

#1917 [DAT-651] - Update summary page when the payment method is by transfer
  .env
  src/App.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.test.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryButton/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryButton/index.test.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.test.js
  src/components/Plans/Checkout/CheckoutSummary/TransferInformation/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XL

#1919 [DAT-863] - fix issue when the user changes the renovation
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
Labels: size/S

#1921 feat: add typeform for free users
  src/components/Dashboard/Dashboard.test.js
  src/components/TypeformSurvey/index.js
  src/components/TypeformSurvey/index.test.js
Labels: size/M
