Repository FromDoppler/doppler-webapp, pull requests merged in 2022-11, with the labels that each got.

#2166 [DAT-1212] - Update content of the messages in the login page
  src/components/Login/Login.js
  src/components/Login/LoginErrorAccountNotValidated.js
  src/components/Signup/SignupConfirmation.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2167 [DAT-1221] - Update message component for the ForgotPassword
  src/components/ForgotPassword/ForgotPassword.js
Labels: size/S

#2168 fix: use environment variables for the generation of the Doppler reports url
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2169 fix: fix not a number ui error on the purchase summary component
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/XS

#2170 [DAT-1218] - Add new messages to show the link to update payment details
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2171 [DAT-1231] - Create a BlockedAccountNotPayed component to show message when the user is blocked by not paid
  src/components/Login/Login.js
Labels: size/M

#2174 fix: change the environment variables
  .env.int
  .env.qa
Labels: size/XS

#2175 feat: add HardcodedSystemUsageSummaryClient in index.js
  src/index.js
Labels: size/XS

#2176 fix: fix language in useBannerData
  src/components/ForgotPassword/ForgotPassword.js
  src/components/Login/Login.js
  src/components/Signup/Signup.js
  src/hooks/useGetBannerData/index.js
  src/hooks/useGetBannerData/index.test.js
Labels: size/M

#2177 feat: change content in Learn with Doppler section
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2165 feat: apply dopplerSystemUsage in firstSteps section
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/FirstSteps/index.test.js
Labels: size/L

#2180 [DAT-1133] - Integrate app with provisory token
  src/components/Login/Login.js
  src/components/PrivateRoute.js
  src/doppler-types.ts
  src/services/app-session.ts
  src/services/doppler-legacy-client.ts
  src/services/sessionmfe-session-manager.ts
Labels: size/M

#2179 Dat 1216 add quick actions
  src/components/Dashboard/CompleteSteps/index.js
  src/components/Dashboard/CompleteSteps/index.test.js
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.test.js
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/components/Dashboard/FirstSteps/ActionBox/index.test.js
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/FirstSteps/index.test.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js
  src/components/Dashboard/QuickActions/index.js
  src/components/Dashboard/QuickActions/index.test.js
  src/components/Dashboard/reducers/completeStepsReducer.js
  src/components/Dashboard/reducers/completeStepsReducer.test.js
  src/components/Dashboard/reducers/firstStepsReducer.js
  src/components/Dashboard/reducers/firstStepsReducer.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-system-usage-api-client.double.ts
  src/services/doppler-system-usage-api-client.test.ts
  src/services/doppler-system-usage-api-client.ts
Labels: size/XXL

#2181 feat: hide SMS option when the user hasn't sms enabled
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.test.js
  src/components/Dashboard/QuickActions/index.js
  src/components/Dashboard/QuickActions/index.test.js
Labels: size/L

#2187 [DAT-1133] - Create a new page to update the payment information and reprocess the pending invoices
  src/App.js
  src/components/Plans/UpdatePaymentInformation/Reducers/reprocessReducer.js
  src/components/Plans/UpdatePaymentInformation/Reducers/updatePaymentInformationReducer.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/UpdatePaymentMethod/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/XXL

#2190 fix: fix warning in App.test.js
  src/App.test.js
Labels: size/XS
