Repository FromDoppler/doppler-webapp, pull requests merged in 2022-01, with the labels that each got.

#1822 [DAT-730] - Fix issue when the promocode is passed by querystring
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/S

#1823 refactor: refactor InvoiceRecipients component
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients.test.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/XL

#1824 [DAT-735] - Add thousand separator number
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
Labels: size/XS

#1825 [DAT-734] - Add thousand separator number in the 'CheckoutSummary' page
  src/components/Plans/Checkout/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary.test.js
Labels: size/S

#1827 [No-ticket] Add Mercado Shops icon in Control Panel
  src/components/ControlPanel/images/mercadoshops_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
  src/services/doppler-user-api-client.double.ts
Labels: size/S

#1826 refactor: refactor PlanPurchase component
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/L

#1830 [DAT-656] - Fix issue when the user copy and paste the credit card number
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
Labels: size/M

#1831 [DAT-745] - Clear CreditCard's fields when the user edit the credit card information
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
Labels: size/XS

#1829 ⚠️ [No-Ticket] Show connection status for Integrations [DO NOT MERGE UNTIL RELEASE 23.7] ⚠️
  src/services/control-panel-service.ts
Labels: size/XS

#1832 Disable status icons
  src/services/control-panel-service.ts
Labels: size/XS

#1834 Activate control panel status
  src/services/control-panel-service.ts
Labels: size/XS

#1835 fix: fix in url dashboard
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1833 [DOI-307] Add promotional ribbons to Control Panel
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.test.js
  src/components/ControlPanel/images/mercadoshops_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/M

#1837 [DOI-406] Replace MercadoLibre icon
  src/components/ControlPanel/images/mercadolibre_icon.png
Labels: size/XS

#1838 [DAT-746] - fix style issues in the billing information section
  .env
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/form-helpers/form-helpers.css
Labels: size/S

#1845 feat: expose data to be used by hotjar
  src/services/doppler-legacy-client.ts
  src/services/session-manager.ts
Labels: size/S

#1846 [DOI-413] Add Microsoft Dynamics 365 icon into control panel
  src/components/ControlPanel/ControlPanel.test.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.test.js
  src/components/ControlPanel/images/dynamics_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#1847 feat: redirect in paids account
  src/App.js
  src/components/Plans/PlanCalculator/GoToUpgrade/index.js
  src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
Labels: size/L

#1848 feat: add credit card icons
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
  src/i18n/en.js
  src/i18n/es.js
  src/img/credit-cards.svg
Labels: size/S
