Repository FromDoppler/doppler-webapp, pull requests merged in 2022-08, with the labels that each got.

#2049 feat: add account type query param by default in upgrade proccess
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/hooks/useUserTypeAsQueryParam/index.js
Labels: size/L

#2054 fix: assume 'direct' when URL does not contain UTM_Source
  src/components/Signup/Signup.js
Labels: size/S

#2053 fix: fix error when the user has account type query param
  src/components/Plans/PlanCalculator/BannerUpgrade/getUpgradeInfo.js
  src/hooks/useUserTypeAsQueryParam/index.js
Labels: size/S

#2052 feat(control panel): remove unopened mails section
  src/services/control-panel-service.ts
Labels: size/XS

#2058 chore(deps): bump node from 15.14.0 to 16.16.0
  Dockerfile
  Dockerfile.BUILDS_AND_CDN
  Dockerfile.LOCAL
  Dockerfile.RELEASES
  Dockerfile.swarm
  build-w-docker.sh
Labels: size/S

#2020 DE-666 - Update MFE loader
  public/index.html
Labels: size/XS

#2059 [DAT-984] - Integrate update between contacts plan
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2062 Try to read referrer hostname as utm_source when it is not included in the query-string
  src/components/Signup/Signup.js
Labels: size/S

#2064 chore: fix typo
  .env.development
  .env.int
  .env.production
  .env.qa
  public/index.html
  src/components/EditorsDemo/EditorsDemo.js
  src/components/MenuDemo/MenuDemo.js
Labels: size/M

#2065 fix: remove maintenance page
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  documentation/deploy-page.md
  documentation/offline-doppler.png
  src/App.js
  src/components/Offline/Offline.js
  src/components/Offline/Offline.styles.js
  src/index.js
  src/services/app-session.ts
  src/services/manual-status-client.ts
  src/services/pure-di.tsx
  src/services/session-manager.ts
Labels: size/L

#2051 Dat 1027 add enable upgrade between plans by contacts - ⚠️⚠️⚠️ don't merge before of 10/08/2022
  src/components/Plans/PlanCalculator/GoToUpgrade/index.js
  src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
Labels: size/L

#2067 chore: add clarification comment in getReferrerHostname
  src/components/Signup/Signup.js
Labels: size/XS

#2068 refactor: remove use of "/features" endpoint
  src/services/doppler-legacy-client.ts
  src/services/doppler-user-api-client.ts
Labels: size/XS

#2069 feat: add HTML support for content description
  src/components/shared/Promotions/Promotions.js
  src/services/doppler-sites-client.doubles.ts
Labels: size/XS

#2081 [DAT-1067] - Integrate new checkout with buy credits
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.ts
Labels: size/M

#2061 DE-554 - Use Session MFE
  public/index.html
  src/components/Header/HeaderMessages/HeaderMessages.js
  src/services/pure-di.tsx
  src/services/session-manager.ts
  src/services/sessionmfe-session-manager.ts
Labels: size/L

#2084 [DAT-1082] - Add enable upgrade between plans by credits
  src/components/Plans/PlanCalculator/GoToUpgrade/index.js
  src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
Labels: size/M

#2085 [DAT-1083] - Filter plan tabs depending the current plan of the user
  src/services/planService/index.test.ts
  src/services/planService/index.ts
Labels: size/M

#2087 ci(confirmation): remove confirmation step in CI
  Jenkinsfile
Labels: size/S

#2086 Dat 1072 add stepper in dashboard
  src/components/Dashboard/CampaignSummary/index.js
  src/components/Dashboard/ContactSummary/index.js
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/components/Dashboard/FirstSteps/ActionBox/index.test.js
  src/components/Dashboard/FirstSteps/Notification/index.js
  src/components/Dashboard/FirstSteps/Notification/index.test.js
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/FirstSteps/index.test.js
  src/components/Dashboard/FirstSteps/reducers/firstStepsReducer.js
  src/components/Dashboard/OverlaySection/index.js
  src/components/Dashboard/OverlaySection/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/dashboardService/SystemUsageSummary.double.ts
Labels: size/L

#2089 [DAT-1085] - Update content to 'months to pay' legend
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2066 Dat 1071 upgrade react router dom v6
  package.json
  src/App.js
  src/App.test.js
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/components/InvoicesList/InvoicesList.js
  src/components/Login/Login.js
  src/components/Plans/Checkout/Checkout.test.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.test.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PurchaseSummary/Promocode.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.test.js
  src/components/PrivateRoute.js
  src/components/PublicRouteWithLegacyFallback.js
  src/components/RedirectToLogin.js
  src/components/RedirectWithQuery.js
  src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.js
  src/components/Reports/ReportsPartialsCampaigns/ReportsPartialsCampaigns.test.js
  src/components/Reports/SubscriberSentCampaigns/SubscriberSentCampaigns.js
  src/components/Reports/Subscribers/Subscribers.js
  src/components/Reports/Subscribers/Subscribers.test.js
  src/components/Reports/Subscribers/SubscribersLegacyUrlRedirect.js
  src/components/SafeRedirect.js
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/components/Signup/SignupConfirmation.js
  src/hooks/useUserTypeAsQueryParam/index.js
  src/services/origin-management.tsx
  yarn.lock
Labels: size/XXL

#2097 [DAT-1088] - Update 'monts to pay' legend for the email plans
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2098 fix: from state to query params
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/components/Signup/SignupConfirmation.js
Labels: size/M

#2100 [DAT-1097] - Fix issue in the dashboard in the stepper.
  src/components/Dashboard/FirstSteps/index.js
Labels: size/XS

#2107 build: remove dependabot
  .github/dependabot.yml
Labels: size/M
