Repository FromDoppler/doppler-webapp, pull requests merged in 2022-04, with the labels that each got.

#1922 chore: update version library
  .env
Labels: size/XS

#1925 feat: add typeform in report page
  src/components/Reports/Reports.js
  src/components/Reports/Reports.test.js
  src/components/SiteTrackingRequired/SiteTrackingRequired.js
  src/components/SiteTrackingRequired/SiteTrackingRequired.test.js
Labels: size/M

#1927 fix: restore previous version
  .env
Labels: size/XS

#1928 [DAT-874] - Add validations for the NIT
  src/components/Plans/Checkout/PaymentMethod/Transfer/Colombia/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/validations.ts
Labels: size/M

#1929 [DAT-876] - Add new endpoints to use in the Mexico transfer
  src/services/static-data-client.double.ts
  src/services/static-data-client.test.ts
  src/services/static-data-client.ts
Labels: size/L

#1930 Update version library to fix the "cucarda" and icons
  .env
Labels: size/XS

#1932 refactor: make refactor in transfer component
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
Labels: size/L

#1931 [DAT-831] - Integrate colombia users to use the new checkout
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/XS

#1934 [DAT-884] - Add RFC validation for the Mexico transfer
  src/i18n/en.js
  src/i18n/es.js
  src/validations.test.js
  src/validations.ts
Labels: size/M

#1936 Dat 601 add transfer mexico
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.test.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
  src/services/static-data-client.ts
Labels: size/L

#1937 Dat 882 add taxes message to total
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#1935 [DAT-885] - Refactor in the mapPaymentMethodToUpdate method
  src/doppler-types.ts
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#1938 [No-ticket] - fix issue when the state.discount is undefined
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/XS

#1939 [DAT-892] - Add asteric in the next billing information
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/XS

#1940 [DAT-891] - fix issue when the user changes the renovation type
  src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.js
Labels: size/S

#1943 feat: add content to dashboard. Replace demo day content in spanish
  src/i18n/es.js
Labels: size/XS

#1945 refactor: refactor test to transfer mexico
  src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.test.js
Labels: size/L

#1944 feat: add transfer argentina
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.test.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Transfer.test.js
Labels: size/L

#1946 fix: menu responsive
  .env
Labels: size/XS

#1949 [DAT-899] - Integrate the free mexican users to use the new checkout
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/XS

#1950 feat: remove cuit validation when consumer type is final consumer
  src/components/Plans/Checkout/PaymentMethod/Transfer/Argentina/index.js
Labels: size/XS

#1951 fix: update the version of the library UI
  .env
Labels: size/XS

#1952 fix: remove warning in console
  src/App.test.js
  src/components/Reports/Reports.js
Labels: size/M

#1953 [DAT-905] - Encode promocode parameter because sometimes this contains special characters
  src/services/doppler-account-plans-api-client.ts
Labels: size/XS

#1954 [DAT-893] - Calculate the total of the next invoice depending of the durati…
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.ts
Labels: size/XS
