Repository FromDoppler/doppler-webapp, pull requests merged in 2022-06, with the labels that each got.

#1996 [DAT-958] - Show first data message when the buy process fail
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/doppler-types.ts
Labels: size/L

#1999 [DAT-970] - Modify card content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2001 [DAT-975] - Update checkout summary when the user has upgrade pending
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.test.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryButton/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryButton/index.test.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.test.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#2002 [No-Ticket] Fix issue in the checkout summary in the title section
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Labels: size/XS

#2003 [DAT-977] - Update security code field in mercado pago
  src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js
Labels: size/XS

#2004 [DAT-978] - Show Mercadopago error in the purchase
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2007 feat: add user email by default to invoice recipients
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.test.js
Labels: size/M

#2009 fix icons in checkout
  src/components/Plans/Checkout/CheckoutSummary/MercadoPagoInformation/index.js
  src/components/Plans/Checkout/CheckoutSummary/TransferInformation/index.js
Labels: size/M

#2010 feat: use the new loader
  public/index.html
Labels: size/XS

#2012 feat: redirect user to /upgrade-sueestion-form when has exclusive plan
  src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
  src/components/Plans/PlanCalculator/index.js
Labels: size/M

#2013 feat: add message for trimestral/semestral/year accounts
  src/components/Plans/PlanCalculator/SubscriptionType/index.js
  src/components/Plans/PlanCalculator/SubscriptionType/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2017 [DAT-1000] - Update checkou summary page when the payment method is MP
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/MercadoPagoInformation/index.js
Labels: size/M

#2018 fix: fix suscription message when account type is free
  src/services/doppler-legacy-client.ts
Labels: size/XS

#2019 feat: add support for plans by contacts to plan calculator
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.test.js
Labels: size/M
