Repository FromDoppler/doppler-webapp, pull requests merged in 2022-07, with the labels that each got.

#2024 [DAT-998] - Integrate the upgrade between plans (only for emails) with the new checkout
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.test.js
  src/components/Plans/Checkout/CheckoutSummary/TransferInformation/index.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.ts
Labels: size/L

#2028 fix: enable button when change the suscription type user
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
  src/components/Plans/PlanCalculator/index.js
Labels: size/M

#2034 [DAT-1042] - change Aprende con Doppler spanish card content.
  src/i18n/es.js
Labels: size/XS

#2035 Dat 1039 add tracking ids to dashboard
  src/components/Dashboard/CampaignSummary/index.js
  src/components/Dashboard/ContactSummary/index.js
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/LearnWithDoppler/Carousel/Slide/Slide.js
  src/components/Dashboard/LearnWithDoppler/index.js
Labels: size/S

#2033 [DAT-1032] - Handle submit logic
  src/components/ValidateSubscribers/ValidateMaxSubscribersConfirm/index.js
  src/components/ValidateSubscribers/ValidateMaxSubscribersConfirm/index.test.js
  src/components/ValidateSubscribers/ValidateMaxSubscribersForm/index.js
  src/components/ValidateSubscribers/index.js
  src/components/ValidateSubscribers/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.test.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#2025 Dat 1013 enabled plans by emails - ⚠️⚠️⚠️ don't merge before of DAT-998
  src/components/Plans/PlanCalculator/GoToUpgrade/index.js
  src/components/Plans/PlanCalculator/GoToUpgrade/index.test.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.test.js
Labels: size/L

#2040 [No-Ticket] fix issue when show the next invoice amount
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/S

#2038 [DAT-999] - Add banner and validate subscribers form
  src/components/Header/Header.js
  src/components/Header/HeaderMessages/HeaderMessages.js
  src/components/Header/HeaderMessages/HeaderMessages.test.js
  src/components/ValidateSubscribers/ValidateMaxSubscribersForm/index.js
  src/components/ValidateSubscribers/index.js
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.ts
Labels: size/L

#2042 Mostrar opción sms en el menu de usuario
  src/components/Header/HeaderUserMenu/HeaderUserMenu.js
  src/components/Header/HeaderUserMenu/HeaderUserMenu.test.js
Labels: size/M

#2043 Dat 1039 add id to dashboard
  src/components/Dashboard/CampaignSummary/index.js
  src/components/Dashboard/ContactSummary/index.js
  src/components/Dashboard/FirstSteps/ActionBox/index.js
  src/components/Dashboard/FirstSteps/index.js
  src/components/Dashboard/Kpis/KpiGroup.js
  src/components/Dashboard/LearnWithDoppler/Carousel/Slide/Slide.js
  src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js
  src/components/Dashboard/LearnWithDoppler/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L
