Repository FromDoppler/doppler-webapp, pull requests merged in 2022-12, with the labels that each got.

#2194 [DAT-1269] - Redirect to the login when the user is cancelated
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
Labels: size/S

#2193 [DAT-1271] - Create update payment information summary
  public/images/error-message.svg
  src/App.js
  src/components/Plans/UpdatePaymentInformation/DeclinedInvoicesList/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/UpdatePaymenInformationSummaryTitle/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.ts
Labels: size/XL

#2192 [DOI-820] Move facebook card to native integrations
  src/services/control-panel-service.ts
Labels: size/S

#2200 feat: remove origin login by default
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
Labels: size/S

#2198 feat: add new method in billing api service
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#2197 [DAT-1273] - Add contact information page when the user has transfer as payment method
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/StatusMessage/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/StatusMessage/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/ContactInformation/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.test.js
  src/components/Plans/UpdatePaymentInformation/index.styles.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/L

#2202 [DAT-1287] - Translate the credit card error in the invoices table
  src/components/Plans/UpdatePaymentInformation/DeclinedInvoicesList/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2208 [DOI-831] Add spinning icon when waiting for status fetch
  src/components/Integrations/index.js
  src/components/Integrations/index.test.js
  src/components/Integrations/reducers/IntegrationReducer.js
  src/components/Integrations/reducers/IntegrationReducer.test.js
Labels: size/L

#2206 [DOI-829] Remove integrations from control panel
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanel.styles.js
  src/components/ControlPanel/ControlPanel.test.js
  src/components/ControlPanel/images/connected.png
  src/components/ControlPanel/images/connection_alert.png
  src/components/ControlPanel/images/disconnected.png
  src/components/ControlPanel/reducers/controlPanelSectionsReducer.js
  src/components/ControlPanel/reducers/controlPanelSectionsReducer.test.js
  src/components/Integrations/images/Tiendanube_icon.svg
  src/components/Integrations/images/Typeform_icon.png
  src/components/Integrations/images/Unbounce_icon.svg
  src/components/Integrations/images/adobe_commerce_icon.png
  src/components/Integrations/images/bigquery_icon.png
  src/components/Integrations/images/bmw_crm_icon.png
  src/components/Integrations/images/dynamics_icon.png
  src/components/Integrations/images/easycommerce_icon.svg
  src/components/Integrations/images/eventbrite_icon.png
  src/components/Integrations/images/facebook_icon.png
  src/components/Integrations/images/facebook_lead_ads_icon.png
  src/components/Integrations/images/go_to_webinar_icon.png
  src/components/Integrations/images/google_analitics_icon.png
  src/components/Integrations/images/hubspot_icon.png
  src/components/Integrations/images/infor_icon.png
  src/components/Integrations/images/lander__icon.png
  src/components/Integrations/images/learnpress_icon.png
  src/components/Integrations/images/magento_icon.png
  src/components/Integrations/images/mercadolibre_icon.png
  src/components/Integrations/images/mercadoshops_icon.png
  src/components/Integrations/images/mitienda-icon.png
  src/components/Integrations/images/optin_monster_icon.png
  src/components/Integrations/images/payu_icon.png
  src/components/Integrations/images/prestashop_icon.png
  src/components/Integrations/images/salesforce_icon.png
  src/components/Integrations/images/shopify_icon.png
  src/components/Integrations/images/tiendup_icon.png
  src/components/Integrations/images/tokko_icon.png
  src/components/Integrations/images/viewed_icon.png
  src/components/Integrations/images/vtex_icon.svg
  src/components/Integrations/images/wix_icon.png
  src/components/Integrations/images/wizell_icon.png
  src/components/Integrations/images/woocommerce_icon.png
  src/components/Integrations/images/xintel_icon.png
  src/components/Integrations/images/zapier_icon.png
  src/components/Integrations/images/zoho_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/XL

#2211 feat: add classname to field group
  src/components/Signup/Signup.js
Labels: size/XS

#2213 [DAT-1271] - Update content in the pages
  src/components/Plans/UpdatePaymentInformation/DeclinedInvoicesList/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/UpdatePaymenInformationSummaryTitle/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2214 fix: fix privacy policy item
  src/components/Signup/Signup.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2212 feat: add inline error
  src/components/Signup/Signup.js
  src/components/form-helpers/form-helpers.js
Labels: size/M

#2215 Dat 1306 add automatic scroll to error
  package.json
  src/App.js
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/components/shared/ScrollToFieldError/index.js
  src/components/shared/ScrollToFieldError/index.test.js
  yarn.lock
Labels: size/L
