Repository FromDoppler/doppler-webapp, pull requests merged in 2022-09, with the labels that each got.

#2121 feat: add new content to email field in signup
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2119 chore: update jenkinsfile
  Jenkinsfile
  build-n-publish.sh
Labels: size/L

#2120 fix: remove class bg message grey
  src/components/SiteTrackingRequired/SiteTrackingRequired.js
Labels: size/XS

#2123 fix: change location for window.location
  src/services/origin-management.tsx
Labels: size/S

#2125 fix: fix cannot read null from null in signup page
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
Labels: size/M

#2126 Disable Renovate auto-rebase
  renovate.json
Labels: size/XS

#2124 fix: fin in signup confirmation
  src/components/Signup/SignupConfirmation.js
  src/components/Signup/SignupConfirmation.styles.js
Labels: size/M

#2127 fix: use query params when the user doesn't accept cookies
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
Labels: size/L

#2129 [DAT-1136] - Add promocode in the promotion object when it is passed from url
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/XS

#2128 fix: remove arrows from headers
  src/components/Dashboard/Dashboard.js
  src/components/Integrations/BigQuery/AuthorizationPage.js
  src/components/shared/HeaderSection/HeaderSection.js
Labels: size/XS

#2132 fix: add reports to login redirection white list
  src/utils.ts
Labels: size/XS

#2131 [DAT-1168] - Disabled the continue button when the user only change the renovation type in the update between plans
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/XS

#2021 DE-720 - Use Menu MFE in Doppler WebApp
  src/App.js
  src/App.test.js
  src/components/EditorsDemo/EditorsDemo.js
  src/components/MenuDemo/MenuDemo.js
  src/components/NewFeatures/NewFeatures.js
  src/components/PrivateRoute.js
Labels: size/M

#2130 Dat 1165 remove first origin field
  src/App.js
  src/components/Signup/Signup.js
  src/services/doppler-legacy-client.ts
  src/services/origin-management.tsx
  src/services/pure-di.tsx
Labels: size/M

#2133 fix: add try catch to mapIdUserToken
  src/services/doppler-legacy-client.ts
Labels: size/S

#2134 [DAT-1169] - Disabled the renovation type component when the current plan of user is the same that it selected
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/reducers/plansByTypeReducer.js
Labels: size/S

#2136 [DAT-1127)] - Show a message to indicate that only support upselling when the does not change the plan in the checkout
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M
