Repository FromDoppler/doppler-webapp, pull requests merged in 2022-10, with the labels that each got.

#2137 fix: fix tabs urls
  src/components/Reports/Subscribers/Subscribers.js
Labels: size/XS

#2142 Fix local environment behavior with dummy session
  public/index.html
Labels: size/XS

#2143 feat: add marks to slider
  src/components/Plans/PlanCalculator/Slider/index.js
  src/components/Plans/PlanCalculator/Slider/index.test.js
Labels: size/L

#2139 Dat 1140 dinamic carousel
  src/components/Dashboard/LearnWithDoppler/Carousel/Carousel.js
  src/components/Dashboard/LearnWithDoppler/Carousel/Carousel.test.js
  src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js
  src/components/Dashboard/LearnWithDoppler/index.js
  src/components/Dashboard/LearnWithDoppler/index.test.js
  src/hooks/useInterval/index.js
  src/hooks/useInterval/index.test.js
Labels: size/L

#2144 DAT-1193 - Fix Shopify page
  src/components/Integrations/Shopify/Shopify.js
  src/components/Integrations/Shopify/Shopify.test.js
  src/utils.test.js
  src/utils.ts
Labels: size/L

#2147 DOI-743 Replace data studio for Looker Studio
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2146 [DOI-725] Add TiendUp to ControlPanel
  src/components/ControlPanel/images/tiendup_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#2149 [DOI-739] Refactor Control Panel URL translation
  src/components/ControlPanel/ControlPanel.js
  src/components/ControlPanel/ControlPanelBox/ControlPanelBox.js
  src/services/control-panel-service.test.ts
  src/services/control-panel-service.ts
Labels: size/L

#2151 fix: remove background grey on plan calculator
  src/components/Plans/PlanCalculator/index.js
  src/components/shared/Promotional/Promotional.js
Labels: size/XS

#2152 fix: Correct grammatical and spelling errors
  src/i18n/es.js
Labels: size/XS

#2145 feat: add page parameter in registration user
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/services/doppler-legacy-client.ts
Labels: size/S

#2153 [DAT-1198] - Update content and component to show the errors in the login page
  src/components/Login/Login.js
  src/components/Login/LoginErrorAccountNotValidated.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2154 [DAT-1198] - Update content for the confirmation page
  src/components/Signup/SignupConfirmation.js
Labels: size/S

#2156 [DAT-1207] - Update the type of messages instead of show warning should show error
  src/components/Login/Login.js
  src/components/form-helpers/form-helpers.js
Labels: size/S

#2155 Dat 1194 apply new layout to shopify
  src/components/Integrations/Shopify/Shopify.js
  src/components/Integrations/Shopify/Shopify.test.js
  src/components/shared/HeaderSection/HeaderSection.js
  src/components/shared/UnexpectedError/index.js
  src/components/shared/UnexpectedError/index.test.js
Labels: size/L

#2157 Dat 1201 get content activation
  src/components/ForgotPassword/ForgotPassword.js
  src/components/Login/Login.js
  src/components/Signup/ConfirmationContent/index.js
  src/components/Signup/ConfirmationContent/index.test.js
  src/components/Signup/Signup.js
  src/components/Signup/SignupConfirmation.js
  src/components/shared/Promotions/Promotions.js
  src/components/shared/Promotions/Promotions.test.js
  src/hooks/useGetBannerData/bannerDataReducer/index.js
  src/hooks/useGetBannerData/bannerDataReducer/index.test.js
  src/hooks/useGetBannerData/index.js
  src/hooks/useGetBannerData/index.test.js
  src/services/doppler-sites-client.ts
Labels: size/L

#2164 Dat 1210 create doppler usage system service
  .env.development
  .env.int
  .env.production
  .env.qa
  src/index.js
  src/services/doppler-system-usage-api-client.double.ts
  src/services/doppler-system-usage-api-client.test.ts
  src/services/doppler-system-usage-api-client.ts
  src/services/pure-di.tsx
Labels: size/L
