Repository FromDoppler/doppler-webapp, pull requests merged in 2022-02, with the labels that each got.

#1851 refactor: refactor PromoCode component
  src/components/Plans/Checkout/PurchaseSummary/Promocode.js
  src/components/Plans/Checkout/PurchaseSummary/Promocode.test.js
Labels: size/L

#1852 Dat 765 refactor purchase summary
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/M

#1854 chore: conventional commits
  commitlint.config.js
  package.json
  prepare.js
  yarn.lock
Labels: size/L

#1859 fix(checkout-summary): Fix issue when redirect checkout summary from old checkout
  src/components/Plans/Checkout/CheckoutSummary.js
Labels: size/XS

#1860 [DAT-787] Only enabled the subscription type is the plan type is by contact
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/M

#1861 [DAT-790] - Missing translations for monthly plan
  src/components/Plans/Checkout/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#1862 Dat 795 refactor plan price component
  src/components/Plans/PlanCalculator/PlanPrice/OldPrice/index.js
  src/components/Plans/PlanCalculator/PlanPrice/OldPrice/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PricePerExtraEmail/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.js
  src/components/Plans/PlanCalculator/PlanPrice/PriceWithDiscount/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/TotalPrice/index.js
  src/components/Plans/PlanCalculator/PlanPrice/TotalPrice/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/index.js
Labels: size/M

#1870 feat(login): modify user input to capture email using datahub
  src/components/Login/Login.js
  src/index.js
Labels: size/XS

#1871 Dat 783 apply promocode to plan calculator
  src/components/Plans/PlanCalculator/Discounts/index.js
  src/components/Plans/PlanCalculator/Discounts/index.test.js
  src/components/Plans/PlanCalculator/PlanPrice/OldPrice/index.js
  src/components/Plans/PlanCalculator/PlanPrice/index.js
  src/components/Plans/PlanCalculator/PlanPrice/index.test.js
  src/components/Plans/PlanCalculator/Slider/index.js
  src/components/Plans/PlanCalculator/Slider/index.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/reducers/promocodeReducer.js
  src/components/Plans/PlanCalculator/reducers/promocodeReducer.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#1872 fix: remove warning message when there is not promocode
  src/components/Plans/PlanCalculator/PlanPrice/index.js
  src/components/Plans/PlanCalculator/PlanPrice/index.test.js
  src/components/Plans/PlanCalculator/index.js
Labels: size/S

#1878 chore: update version library
  .env
Labels: size/XS

#1879 fix: change shopify url reference
  .env.production
Labels: size/XS

#1880 [DAT-803] - Update logic to include the plan by contacts to redirect new checkout
  src/components/Plans/PlanCalculator/PlanCalculatorButtons/index.js
Labels: size/XS

#1881 [DOI-462] Add MiTienda into ControlPanel
  src/components/ControlPanel/images/mitienda-icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
  src/services/doppler-user-api-client.double.ts
Labels: size/S
