Repository FromDoppler/doppler-webapp, pull requests merged in 2023-07, with the labels that each got.

#2304 Dat 1581 create shopping cart component
  src/components/BuyProcess/ShoppingCart/BuyButton/index.js
  src/components/BuyProcess/ShoppingCart/BuyButton/index.test.js
  src/components/BuyProcess/ShoppingCart/Clarification/index.js
  src/components/BuyProcess/ShoppingCart/Clarification/index.test.js
  src/components/BuyProcess/ShoppingCart/ItemCart/index.js
  src/components/BuyProcess/ShoppingCart/ItemCart/index.test.js
  src/components/BuyProcess/ShoppingCart/index.js
Labels: size/XL

#2297 feat: add upload field item in payment method
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#2300 feat: add front end validation to expiry date
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/validations.ts
Labels: size/S

#2318 feat: remove tax regime & tax certificate when transfer is dintict to…
  src/services/doppler-billing-user-api-client.ts
Labels: size/S

#2324 Dat 1604 upgrade prettier
  package.json
  public/index.html
  src/components/shared/C3Chart/C3Chart.styles.js
  yarn.lock
Labels: size/S

#2345 [DAT-1609] - Map new clover error
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/UpdatePaymentInformation/DeclinedInvoicesList/index.js
  src/components/Plans/UpdatePaymentInformation/index.js
  src/doppler-types.ts
Labels: size/XS

#2349 Dat 1598 zip code required
  src/components/Plans/Checkout/ContactInformation/ContactInformation.js
  src/components/Plans/Checkout/ContactInformation/ContactInformation.test.js
Labels: size/XS

#2353 feat: add new breadcrumb
  src/components/shared/BreadcrumbNew/index.js
  src/components/shared/BreadcrumbNew/index.test.js
Labels: size/M

#2361 Dat 1614 create create new discount component
  src/components/BuyProcess/PaymentFrequency/index.js
  src/components/BuyProcess/PaymentFrequency/index.test.js
  src/components/BuyProcess/RadioBox/index.js
  src/components/BuyProcess/RadioBox/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2362 [DOI-1027] modify jumpseller link
  src/services/control-panel-service.ts
Labels: size/XS

#2363 [DAT-1622] - Add new prefix to validate cuit
  src/validations.test.js
  src/validations.ts
Labels: size/S
