Repository FromDoppler/doppler-webapp, pull requests merged in 2023-05, with the labels that each got.

#2288 feat: modify invoice recipipients in billing information section
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.js
  src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.test.js
Labels: size/M

#2287 [DAT-1399] - Integrate change credit plans to contacts or email plans
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
  src/components/Plans/PlanCalculator/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/planService/index.test.ts
  src/services/planService/index.ts
Labels: size/M

#2283 [DAT-1439] - add tax regime field for mex transf
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/Plans/Checkout/BillingInformation/BillingInformation.test.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.js
  src/components/Plans/Checkout/PaymentMethod/Transfer/Mexico/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
  src/services/static-data-client.double.ts
  src/services/static-data-client.test.ts
  src/services/static-data-client.ts
Labels: size/L

#2290 [DAT-1490]- Show new message when the plan is monthly
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2291 feat: add container to save and continue button
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/Plans/Checkout/ContactInformation/ContactInformation.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/Step/Step.js
Labels: size/M

#2289 feat: add new zendesk
  src/App.js
  src/utils.ts
Labels: size/XS

#2292 [DAT-1523] - Update legend for the exceedent cost email message
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS
