Repository FromDoppler/doppler-webapp, pull requests merged in 2023-10, with the labels that each got.

#2405 feat: add info about plan to radio to plan-selection
  src/components/BuyProcess/NavigationTabs/index.js
  src/components/BuyProcess/RadioBox/index.js
  src/components/BuyProcess/RadioBox/index.test.js
Labels: size/S

#2269 [DOI-894] Change Shopify UI to display array of lists
  src/components/Integrations/Shopify/Shopify.js
  src/components/Integrations/Shopify/Shopify.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-api-client.double.ts
  src/services/doppler-api-client.ts
  src/services/shopify-client.doubles.ts
  src/services/shopify-client.test.ts
  src/services/shopify-client.ts
Labels: size/L

#2406 [DOI-894] Fix issues in shopify UI
  src/components/Integrations/Shopify/Shopify.js
  src/services/shopify-client.ts
Labels: size/M

#2407 feat: create use default plan type hook
  src/hooks/useDefaultPlanType/index.js
  src/hooks/useDefaultPlanType/index.test.js
Labels: size/L

#2409 feat: enable contact policy time restriction section
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
Labels: size/L

#2412 DOP-1463 - update twitter logo
  src/components/ControlPanel/images/auto_publish_icon.png
Labels: size/XS

#2411 [DAT-1689.supportAutomaticDebit] Add automatic debit component
  src/components/Plans/Checkout/PaymentMethod/AutomaticDebit/Argentina/index.js
  src/components/Plans/Checkout/PaymentMethod/AutomaticDebit/Argentina/index.test.js
  src/components/Plans/Checkout/PaymentMethod/AutomaticDebit/AutomaticDebit.js
  src/components/Plans/Checkout/PaymentMethod/AutomaticDebit/AutomaticDebit.test.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/form-helpers/form-helpers.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
  src/validations.test.js
  src/validations.ts
Labels: size/XL

#2415 feat: add new payment frequency component
  src/components/BuyProcess/PaymentFrequency/SubscriptionType/index.js
  src/components/BuyProcess/PaymentFrequency/SubscriptionType/index.test.js
  src/components/BuyProcess/PaymentFrequency/index.js
  src/components/BuyProcess/PaymentFrequency/index.test.js
  src/components/BuyProcess/PaymentFrequency/reducers/paymentFrequencyReducer.js
Labels: size/L

#2417 feat: add ip notification to login
  src/components/Login/Login.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
Labels: size/M

#2418 [no-task] update messages content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2419 [No-Task] - Update message content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2420 [DAT-1766] Show a new message when the user is pending to confirmation
  src/components/Login/Login.js
  src/services/doppler-legacy-client.ts
Labels: size/XS

#2421 [DAT-1773] - Remove disabled login button
  src/components/Login/Login.js
Labels: size/XS

#2422 [DAT-1768] - Change componet for the access denied message
  src/components/Login/Login.js
Labels: size/XS

#2423 [No-Task] Change size error message
  src/components/form-helpers/form-helpers.js
Labels: size/XS
