Repository FromDoppler/doppler-webapp, pull requests merged in 2023-09, with the labels that each got.

#2389 fix(deps): update dependency typescript to v4.5
  package.json
  yarn.lock
Labels: size/S

#2390 Dop 1445 improve contact policy errors messages
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
Labels: size/L

#2391 chore(NavigationTabs): update component
  src/components/BuyProcess/NavigationTabs/index.js
  src/components/BuyProcess/NavigationTabs/index.test.js
Labels: size/M

#2392 chore(PaymentFrequency): update component
  src/components/BuyProcess/PaymentFrequency/index.js
  src/components/BuyProcess/PaymentFrequency/index.test.js
Labels: size/M

#2393 chore(ItemCart): update item cart component
  src/components/BuyProcess/ShoppingCart/ItemCart/index.js
  src/components/BuyProcess/ShoppingCart/ItemCart/index.test.js
Labels: size/M

#2394 feat: add get plan billing details data endpoint
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.ts
Labels: size/M

#2395 feat: create use payment method data hook
  src/hooks/usePaymentMethodData/index.js
  src/hooks/usePaymentMethodData/index.test.js
Labels: size/M

#2396 feat: create checkout link component
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.style.js
Labels: size/L

#2397 feat: add plan types view
  package.json
  src/App.js
  src/components/BuyProcess/PlanTypes/PlanTypeCard/index.js
  src/components/BuyProcess/PlanTypes/index.js
  src/components/NewFeatures/NewFeatures.js
  src/i18n/en.js
  src/i18n/es.js
  yarn.lock
Labels: size/XL

#2399 feat: change account type in plan selection and checkout
  src/components/BuyProcess/PlanTypes/PlanTypeCard/index.js
  src/components/BuyProcess/PlanTypes/index.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/PlanCalculator/BannerUpgrade/BannerUpgrade.js
  src/components/Plans/PlanCalculator/BannerUpgrade/getUpgradeInfo.js
  src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.js
  src/components/Plans/PlanCalculator/NavigatorTabs/NavigatorTabs.test.js
  src/components/Plans/PlanCalculator/index.js
  src/components/Plans/PlanCalculator/index.test.js
  src/utils.ts
Labels: size/L

#2400 [DAT-1684] - Integrate canceled account with mercado pago
  src/components/Plans/UpdatePaymentInformation/Reducers/updatePaymentInformationReducer.js
  src/components/Plans/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js
Labels: size/L

#2402 fix: add redirect when the user is not a free user
  src/components/BuyProcess/PlanTypes/index.js
Labels: size/S

#2403 [DAT-1704] - Support change the payment method to Ar transfer
  src/components/Plans/UpdatePaymentInformation/Reducers/reprocessReducer.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/UpdatePaymenInformationSummaryTitle/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2404 [DOI-1084] Add wordpress card in integrations section
  src/components/Integrations/images/wordpress_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S
