Repository FromDoppler/doppler-webapp, pull requests merged in 2023-03, with the labels that each got.

#2260 [DOI-890] Remove lander from integrations section
  src/components/Integrations/images/lander__icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#2267 feat: add more quick actions items
  src/components/Dashboard/Dashboard.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2266 feat: remove CompleteSteps button
  src/components/Dashboard/CompleteSteps/index.js
  src/components/Dashboard/Dashboard.js
Labels: size/M

#2268 feat: change content in learn with doppler section
  src/i18n/es.js
Labels: size/XS

#2272 Dat 1416 checkout UI
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/Plans/Checkout/BillingInformation/BillingInformation.test.js
  src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.js
  src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
Labels: size/L

#2273 Revert "Dat 1416 checkout UI"
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/Plans/Checkout/BillingInformation/BillingInformation.test.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.js
  src/components/Plans/Checkout/PurchaseSummary/InvoiceRecipients/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
Labels: size/L

#2274 Revert "Revert "Dat 1416 checkout UI""
  src/components/Plans/Checkout/BillingInformation/BillingInformation.js
  src/components/Plans/Checkout/BillingInformation/BillingInformation.test.js
  src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.js
  src/components/Plans/Checkout/BillingInformation/InvoiceRecipients/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.test.js
Labels: size/L
