Repository FromDoppler/doppler-webapp, pull requests merged in 2023-06, with the labels that each got.

#2294 [DAT-1527] - Pass the new payment status error to the api and apply new styles
  src/components/Plans/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
Labels: size/S

#2295 Dat 1530 add accessible fields
  src/components/ForgotPassword/ForgotPassword.js
  src/components/Login/Login.js
  src/components/form-helpers/form-helpers.js
Labels: size/L

#2298 feat: create new slider component
  src/components/BuyProcess/Slider/index.js
  src/components/BuyProcess/Slider/index.test.js
Labels: size/L

#2299 [DAT-1580] - Add clover error messages
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PurchaseSummary/PlanPurchase/index.js
  src/components/Plans/UpdatePaymentInformation/DeclinedInvoicesList/index.js
  src/components/Plans/UpdatePaymentInformation/index.js
  src/doppler-types.ts
Labels: size/M

#2296 feat: add accessible fields to signup form
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/components/form-helpers/form-helpers.js
Labels: size/L

#2302 fix: add null validation to description in discount component
  src/components/Plans/Checkout/Discounts/Discounts.js
Labels: size/XS

#2303 fix: fix discount percentage in discount component
  src/components/Plans/Checkout/Discounts/Discounts.js
Labels: size/XS
