Repository FromDoppler/doppler-webapp, pull requests merged in 2023-01, with the labels that each got.

#2218 [DAT-1308] - Change steps in the main page
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/Reprocess/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/UpdatePaymentMethod/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2217 feat: add accordion
  src/components/Signup/Signup.js
  src/components/Signup/Signup.styles.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2210 [DOI-776] Add Jumpseller to integrations section
  src/components/Integrations/images/jumpseller_icon.svg
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
  src/services/doppler-user-api-client.double.ts
Labels: size/M

#2220 [DOI-776] Adjust control panel box icons size
  src/components/shared/ControlPanelBox/ControlPanelBox.styles.js
Labels: size/XS

#2219 Dat 1303 content improvement in signup
  src/components/Signup/Signup.js
  src/components/Signup/Signup.styles.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2223 fix: fix redirect to webapp pages after login
  src/components/Login/Login.js
  src/components/Login/Login.test.js
Labels: size/M

#2221 [DOI-840] Change breadcrumb links for Shopify and BigQuery
  src/components/Integrations/BigQuery/AuthorizationPage.js
  src/components/Integrations/Shopify/Shopify.js
  src/components/Integrations/Shopify/Shopify.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2224 fix: fix link privacy policy in signup
  src/components/Signup/Signup.styles.js
Labels: size/XS

#2227 [No-Ticket] Remove Jumpseller from integrations section
  src/services/control-panel-service.ts
Labels: size/S

#2222 feat: update confirmation page
  src/components/Signup/ConfirmationContent/index.js
  src/components/Signup/ConfirmationContent/index.test.js
  src/components/Signup/DefaultConfirmationContent/index.js
  src/components/Signup/DefaultConfirmationContent/index.test.js
  src/components/Signup/DynamicConfirmationContent/index.js
  src/components/Signup/DynamicConfirmationContent/index.test.js
  src/components/Signup/Signup.test.js
  src/components/Signup/SignupConfirmation.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2231 [DAT-1317] - Update transfer component
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformation/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2225 [DAT-1284] - Integrate update payment method with login
  src/components/Login/Login.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
Labels: size/M

#2232 [DOI-842] Use Link component when redirecting inside Webapp for breadcrumb
  src/components/DopplerPlus/AgenciesForm.test.js
  src/components/Integrations/BigQuery/AuthorizationPage.test.js
  src/components/Integrations/Shopify/Shopify.test.js
  src/components/shared/Breadcrumb/Breadcrumb.js
  src/components/shared/Breadcrumb/Breadcrumb.test.js
Labels: size/L

#2233 [DOI-847] Resize jumpseller icon
  src/components/Integrations/images/jumpseller_icon.svg
Labels: size/M

#2235 feat: add ids to quick actions
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/QuickActions/index.js
Labels: size/XS

#2236 fix: content improvement sign up
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2199 feat: add beamerId
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/MenuDemo/MenuDemo.js
Labels: size/XS

#2237 feat: refactor update payment information
  src/App.js
  src/components/Plans/UpdatePaymentInformation/ContactInformation/StatusMessage/index.js
  src/components/Plans/UpdatePaymentInformation/ContactInformation/StatusMessage/index.test.js
  src/components/Plans/UpdatePaymentInformation/ContactInformation/index.js
  src/components/Plans/UpdatePaymentInformation/ContactInformation/index.test.js
  src/components/Plans/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/Reprocess/index.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js
  src/components/Plans/UpdatePaymentInformation/index.js
  src/components/Plans/UpdatePaymentInformation/index.test.js
Labels: size/M

#2238 feat: remove target of quick actions
  src/components/Dashboard/QuickActions/index.js
Labels: size/XS

#2239 fix: change confirmation email resend limit
  src/components/Signup/DefaultConfirmationContent/index.js
  src/components/Signup/DefaultConfirmationContent/index.test.js
  src/components/Signup/DynamicConfirmationContent/index.js
  src/components/Signup/DynamicConfirmationContent/index.test.js
Labels: size/XS

#2240 feat: change label of button
  src/i18n/es.js
Labels: size/XS

#2241 [DAT-1350] - Include failed status to get invoices
  src/components/Plans/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
Labels: size/XS
