Repository FromDoppler/doppler-webapp, pull requests merged in 2023-04, with the labels that each got.

#2276 feat: add zigzag
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/M

#2277 feat: add taxes-excluded class to li and delete span
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
Labels: size/XS

#2278 [DAT-1412] - Add new message when the user has positive balance
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2282 [dat-1442] - Update content in Learn with Doppler section
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2271 DE-971 - Compatibility with the new jenkins
  .dockerignore
  .doppler-ci
  doppler-jenkins-ci.groovy
  verify-n-generate-release-w-docker.sh
Labels: size/XS

#2284 [DAT-1455] - fix CI failures
  .gitlint
  .lintstagedrc.js
  .prettierignore
  .prettierrc
  README.md
  build-n-create-docker-image.sh
  build-n-publish-release-w-docker.sh
  build-w-docker.sh
  commitlint.config.js
  package.json
  prepare.js
  public/index.html
  public/manifest.json
  publish-commit-image-to-dockerhub.sh
  renovate.json
  run-docker-container.sh
  run-w-docker-local.sh
  src/.stylelintrc.json
  src/headerData-alerts.json
  src/headerData-for-client-manager-user.json
  src/headerData.json
  src/i18n/README.md
  tsconfig.json
  verify-n-generate-release-w-docker.sh
  verify-w-docker.sh
  watch-w-docker.sh
Labels: size/XXL

#2286 Remove Style Guide deprecated flag
  public/index.html
Labels: size/XS
