Repository FromDoppler/doppler-webapp, pull requests merged in 2023-08, with the labels that each got.

#2365 Dat 1617 create navigation tab component
  src/components/BuyProcess/NavigationTabs/index.js
  src/components/BuyProcess/NavigationTabs/index.test.js
  src/components/BuyProcess/RadioBox/index.js
  src/components/BuyProcess/RadioBox/index.test.js
Labels: size/L

#2373 feat: adjust slider to new design
  src/components/BuyProcess/Slider/index.js
  src/components/BuyProcess/Slider/index.test.js
Labels: size/M

#2381 [DAT-1631] chore: add a new status to the invoices query
  src/components/Plans/UpdatePaymentInformation/Reprocess/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
Labels: size/XS

#2382 [DAT-1649] chore: set default id selected plan value
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
Labels: size/XS

#2383 feat: add content to learn with doppler section
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2384 Dop 1445 get restriction time values from doppler api
  src/services/doppler-contact-policy-api-client.double.ts
  src/services/doppler-contact-policy-api-client.test.ts
  src/services/doppler-contact-policy-api-client.ts
Labels: size/M

#2385 Dop 1445 add contact policy time restriction in control panel
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-contact-policy-api-client.test.ts
  src/services/doppler-contact-policy-api-client.ts
Labels: size/XL

#2386 Dop 1445 add submit form validations
  src/components/ContactPolicy/ContactPolicy.js
  src/components/ContactPolicy/ContactPolicy.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L
