Repository FromDoppler/doppler-webapp, pull requests merged in 2023-11, with the labels that each got.

#2424 feat: add anchor to plan types
  src/components/BuyProcess/PlanTypes/FeaturesPlanTypes/index.js
  src/components/BuyProcess/PlanTypes/index.js
Labels: size/M

#2425 fix: remove inline style in messages
  src/components/form-helpers/form-helpers.js
Labels: size/XS

#2426 feat: add number format option global variable
  src/doppler-types.ts
Labels: size/XS

#2428 [DAT-1695] - Include automatic debit when the user is blocked
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
Labels: size/S
