Repository FromDoppler/doppler-webapp, pull requests merged in 2024-03, with the labels that each got.

#2454 feat: add emms spanish content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2455 [DAT-1904] Allow change redirection on updating payment information
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentInformationSummary/index.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.js
  src/components/Plans/UpdatePaymentInformation/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2456 [DOI-1173] Add Empretienda to integrations section
  src/components/Integrations/images/empretienda_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#2453 Dat 1883 add exclusive discount to shopping cart
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/BuyProcess/PaymentFrequency/index.js
  src/components/BuyProcess/PlanSelection/index.js
  src/components/BuyProcess/PlanTypes/PlanTypeCard/index.js
  src/components/BuyProcess/PlanTypes/index.js
  src/components/BuyProcess/PlanTypes/useGetMinPriceContactArgentina/index.js
  src/components/BuyProcess/PlanTypes/useGetMinPriceContactArgentina/reducers/promocodeReducer.js
  src/components/BuyProcess/PlanTypes/useGetMinPriceContactArgentina/reducers/promocodeReducer.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
  src/components/BuyProcess/ShoppingCart/Promocode/index.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/Plans/Checkout/Checkout.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
  src/services/planService/index.ts
Labels: size/XL
