Repository FromDoppler/doppler-webapp, pull requests merged in 2024-11, with the labels that each got.

#2562 [doi-1632] set empretienda hidden
  src/services/control-panel-service.ts
Labels: size/XS

#2565 [DOI-1670] Add collaborators permission configuration step
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.js
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorPermissionsForm.js
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorPermissionsForm.test.js
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.ts
Labels: size/L

#2567 [DAT-2271]
  src/components/Conversations/index.js
  src/components/Conversations/index.test.js
Labels: size/S

#2566 [DAT-2239] - Add buy on site plan functionality
  src/App.js
  src/components/BuyProcess/BuyProcessLayout/index.js
  src/components/BuyProcess/OnSitePlanSelection/BannerUpgrade/index.js
  src/components/BuyProcess/OnSitePlanSelection/BannerUpgrade/index.test.js
  src/components/BuyProcess/OnSitePlanSelection/OnSitePlanInformation/index.js
  src/components/BuyProcess/OnSitePlanSelection/OnSitePlanInformation/index.test.js
  src/components/BuyProcess/OnSitePlanSelection/PlanBenefits/index.js
  src/components/BuyProcess/OnSitePlanSelection/PlanBenefits/index.test.js
  src/components/BuyProcess/OnSitePlanSelection/SelectedOnSitePlan/index.js
  src/components/BuyProcess/OnSitePlanSelection/SelectedOnSitePlan/index.test.js
  src/components/BuyProcess/OnSitePlanSelection/index.js
  src/components/BuyProcess/OnSitePlanSelection/index.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/OnSite/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/OnSite/index.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/OnSite/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/OnSite/index.test.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/OnSitePlanInformation/index.js
  src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.js
  src/doppler-types.ts
  src/hooks/useFetchOnSitePlans/index.js
  src/hooks/useFetchOnSitePlans/index.test.js
  src/hooks/useFetchOnSitePlans/onSitePlansReducer/index.js
  src/hooks/useFetchOnSitePlans/onSitePlansReducer/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.ts
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
  src/services/doppler-legacy-client.ts
Labels: size/XXL

#2569 fix typo
  src/services/doppler-legacy-client.ts
Labels: size/XS

#2570 [Task-2277] Update zendesk script
  public/index.html
Labels: size/XS

#2571 [DAT-2284] Update card content
  src/i18n/es.js
Labels: size/XS

#2572 [DAT-1961] - Add check digit verification for the credit card
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
  src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/Plans/UpdatePaymentInformation/UpdatePaymentMethod/index.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/validations.test.js
  src/validations.ts
Labels: size/L

#2573 Dat 2278
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/MenuDemo/MenuDemo.js
Labels: size/S

#2574 [DAT-2258] - Add card for the onsite plan in the checkout summary
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummery.test.js
  src/hooks/useFetchOnSitePlans/onSitePlansReducer/index.js
  src/hooks/useFetchOnSitePlans/onSitePlansReducer/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2575 [DAT-2265] - Add slider for the onsite plan
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2576 [no-task] - Set in true the flag of buy onsite plan for the qa environment
  .env.qa
Labels: size/XS
