Repository FromDoppler/doppler-webapp, pull requests merged in 2024-10, with the labels that each got.

#2554 Always allow buy conversation plan
  src/components/BuyProcess/BuyProcessLayout/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/Plans/Checkout/Checkout.js
Labels: size/M

#2555 [DAT-2199] Redirect users with convertsetion active or cms
  src/components/Conversations/index.js
  src/components/Conversations/index.test.js
Labels: size/M

#2557 Add landing plural message
  src/components/BuyProcess/LandingPacksSelection/LandingPacks/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2556 [DOI-1632] Enable empretienda
  src/services/control-panel-service.ts
Labels: size/XS

#2558 Formatting improvement for landing plural message
  src/components/BuyProcess/LandingPacksSelection/LandingPacks/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2559 [DAT-2229] Uppdate dashboard's slider content
  src/i18n/es.js
Labels: size/XS
