Repository FromDoppler/doppler-webapp, pull requests merged in 2024-07, with the labels that each got.

#2490 [DOI-1391] Add collaborator invitation steps
  src/App.js
  src/components/ControlPanel/ColaboratorsSections/Modal/index.js
  src/components/ControlPanel/ColaboratorsSections/index.js
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.js
  src/components/ControlPanel/CollaboratorsSections/Forms/SuccessStepForm.js
  src/components/ControlPanel/CollaboratorsSections/Forms/SuccessStepForm.test.js
  src/components/ControlPanel/CollaboratorsSections/Modal/index.js
  src/components/ControlPanel/CollaboratorsSections/Modal/index.test.js
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.ts
Labels: size/XL

#2491 [DAT-2085] - Update content for the landing pop up
  src/i18n/es.js
Labels: size/XS

#2492 [DOI-1511] Get user invitations through doppler-users API
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.test.ts
  src/services/doppler-user-api-client.ts
Labels: size/L

#2494 [No ticket] Replace Modal component
  src/components/ControlPanel/CollaboratorsSections/Modal/index.js
  src/components/ControlPanel/CollaboratorsSections/Modal/index.test.js
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/components/Modal/Modal.js
Labels: size/L

#2496 [DAT-2070] Remove overflow hidden style from body after survey form is closed
  src/components/Dashboard/Dashboard.js
  src/components/TypeformSurvey/index.js
Labels: size/S

#2493 Feat: Se agrega el logo de Zeus
  src/components/Integrations/images/logo-zeus.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#2497 [DOW-1316] Collaboration invite acceptance view
  src/App.js
  src/components/CollaborationInvite/index.js
  src/components/CollaborationInvite/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.test.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#2495 [DAT-1865] Add conversation plan layout
  package.json
  src/App.js
  src/components/BuyProcess/BuyProcessLayout/index.js
  src/components/BuyProcess/PlanChat/PlanBenefits/index.js
  src/components/BuyProcess/PlanChat/PlanBenefits/index.test.js
  src/components/BuyProcess/PlanChat/PlanChatInfo/index.js
  src/components/BuyProcess/PlanChat/PlanChatInfo/index.test.js
  src/components/BuyProcess/PlanChat/SelectedPlanChat/index.js
  src/components/BuyProcess/PlanChat/SelectedPlanChat/index.test.js
  src/components/BuyProcess/PlanChat/index.js
  src/components/BuyProcess/PlanChat/index.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
  src/components/BuyProcess/ShoppingCart/NextInvoices/index.js
  src/components/BuyProcess/ShoppingCart/NextInvoices/index.test.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/BuyProcess/Stepper/index.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/doppler-types.ts
  src/hooks/useFetchConversationPlans/conversationPlansReducer/index.js
  src/hooks/useFetchConversationPlans/conversationPlansReducer/index.test.js
  src/hooks/useFetchConversationPlans/index.js
  src/hooks/useFetchConversationPlans/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.test.ts
  src/services/doppler-account-plans-api-client.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/XXL

#2498 [DAT-2091] Add contents for the conversations plan
  src/components/BuyProcess/PlanChat/PlanBenefits/index.js
  src/components/BuyProcess/PlanChat/PlanChatInfo/index.js
  src/components/BuyProcess/PlanChat/SelectedPlanChat/index.js
  src/components/BuyProcess/PlanChat/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2499 [DOI-1394] Add functiotionality to dropdown menu
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.js
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.test.js
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/components/ControlPanel/CollaboratorsSections/index.test.js
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.test.ts
  src/services/doppler-user-api-client.ts
Labels: size/L

#2500 [DOI-1316] Fix typo
  src/components/CollaborationInvite/index.js
Labels: size/XS

#2501 [DOI-1316] fix typo and error message display
  src/components/CollaborationInvite/index.js
Labels: size/S

#2502 [DOI-1524] Add session restart after successful invite
  src/components/CollaborationInvite/index.js
Labels: size/XS

#2503 [DAT-2106] Integrate with the success page
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.test.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/PlanChatInformation/index.js
  src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/L

#2504 [DOI-1527] Add validation to prevent users invite themselves as collaborator
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.js
  src/components/ControlPanel/CollaboratorsSections/Forms/CollaboratorInviteForm.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2505 [DOI-1532] Hidde reinvite option when status approved
  src/components/ControlPanel/CollaboratorsSections/index.js
Labels: size/S

#2506 [DOI-1531] Changes to content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S
