Repository FromDoppler/doppler-webapp, pull requests merged in 2024-06, with the labels that each got.

#2474 Dat 2045 improve landing packs
  src/App.js
  src/components/BuyProcess/LandingPacksSelection/index.js
  src/components/BuyProcess/LandingPacksSelection/reducers/deleteLandingPagesReducer.js
  src/components/BuyProcess/LandingPacksSelection/reducers/deleteLandingPagesReducer.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.test.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#2475 fix: fix modal landing plan
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Labels: size/XS

#2476 [DAT-2045] Add new translations
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2477 [No-Task] Change correct my landings url
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/BuyProcess/LandingPacksSelection/LandingPacksMessages/index.js
Labels: size/S

#2478 [DAT-2055] - Update translations for the downgrade or cancellation landing plan
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2479 [DAT-2055] - Update message component
  src/components/BuyProcess/LandingPacksSelection/LandingPacksMessages/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2480 [DAT-2056] Change position cancel message
  src/components/BuyProcess/LandingPacksSelection/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
Labels: size/M

#2481 [DOI-1314] Add colaborators section
  src/App.js
  src/components/ControlPanel/ColaboratorsSections/Modal/index.js
  src/components/ControlPanel/ColaboratorsSections/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2482 [DAT-2059] - Change type message
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Labels: size/XS

#2483 [DAT-2064] Send fingerprint when user is created
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/services/doppler-legacy-client.ts
Labels: size/XS

#2484 [DAT-2048] - Update dashboard cards
  src/components/Dashboard/LearnWithDoppler/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2485 [No Task] - Fix typo issue
  src/i18n/es.js
Labels: size/XS

#2486 Fix issue
  src/i18n/es.js
Labels: size/XS

#2488 [DAT-2072] - Update landings card url
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2487 feat: redirect to plan ypes
  src/components/BuyProcess/LandingPacksSelection/index.js
Labels: size/XS

#2489 [DOI-1313] Add collaborators box in control panel
  src/App.js
  src/components/ControlPanel/images/collaborators_icon.svg
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.ts
Labels: size/M
