Repository FromDoppler/doppler-webapp, pull requests merged in 2024-09, with the labels that each got.

#2533 [DOI-1574] Change contents on promotional page for conversations
  src/components/Conversations/Conversaciones.png
  src/components/Conversations/index.js
  src/components/Conversations/index.test.js
  src/components/Conversations/screenShot.png
  src/components/shared/Promotional/Promotional.js
  src/components/shared/Promotional/Promotional.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2534 DOi-1574 Reduce margin promotional page conversations
  src/components/Conversations/index.js
Labels: size/XS

#2535 chore: change pic
  src/components/Conversations/Conversaciones.png
Labels: size/XS

#2537 [No-Task] Fix issue when try to buy landings
  package.json
  src/components/BuyProcess/LandingPacksSelection/LandingPacks/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
Labels: size/M

#2540 Update text of conversation buy summary
  src/components/Plans/Checkout/CheckoutSummary/PlanChatInformation/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2538 [DOI-1576] Add modal to promotional page
  package.json
  src/components/Conversations/Conversaciones.png
  src/components/Conversations/index.js
  src/components/Modal/Modal.js
  src/components/shared/Promotional/Promotional.js
  yarn.lock
Labels: size/L

#2539 DOI-1579 promotional page contents
  src/components/Conversations/index.js
  src/components/shared/Promotional/Promotional.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2541 [DOI-1576] Add margin top to image
  src/components/shared/Promotional/Promotional.js
Labels: size/XS

#2542 Allow skip marketing step
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
Labels: size/XS

#2543 feat: update first dashboard card content
  src/i18n/es.js
Labels: size/XS

#2536 [DAT-2161] Set in true buy conversations plan in the PROD environment
  .env.production
Labels: size/XS

#2544 Change conversation's promotional video
  src/components/Conversations/index.js
Labels: size/XS

#2545 Change landing plans modal opacity
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
Labels: size/XS

#2473 [DOI-1389] Complete registration of colaborator
  src/components/Signup/Signup.js
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.ts
Labels: size/M

#2547 [DOI-1377] Add collaborator popup in signup page
  src/components/Login/Login.js
  src/components/Signup/Signup.js
  src/components/Signup/Signup.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.test.js
  src/services/doppler-legacy-client.ts
Labels: size/XL

#2548 Update card content
  src/i18n/es.js
Labels: size/XS

#2549 [DOi-1628] Hidde password in collaborator signup
  src/components/Signup/Signup.js
  src/components/form-helpers/form-helpers.js
Labels: size/S

#2550 [DAT-2190] - Add new translations for the WhatsApp benefits
  src/components/BuyProcess/PlanChat/PlanBenefits/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2551 [DAT-2192] - Update 200 conversations instead of 500 and shoe three decimals
  src/components/BuyProcess/PlanChat/PlanBenefits/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2552 [DOI-1593] Add empretienda icon
  src/components/Integrations/images/logo-zeus.png
  src/components/Integrations/images/zeus_icon.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#2553 [DAT-2133] - Support plan more 2000 conversations
  src/components/BuyProcess/PlanChat/BannerUpgrade/index.js
  src/components/BuyProcess/PlanChat/PlanBenefits/index.js
  src/components/BuyProcess/PlanChat/SelectedPlanChat/index.js
  src/components/BuyProcess/PlanChat/index.js
  src/components/BuyProcess/PlanChat/index.test.js
  src/components/BuyProcess/Slider/index.js
  src/hooks/useFetchConversationPlans/conversationPlansReducer/index.js
  src/hooks/useFetchConversationPlans/index.js
  src/hooks/useFetchConversationPlans/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-account-plans-api-client.double.ts
  src/services/doppler-account-plans-api-client.ts
  src/services/doppler-legacy-client.ts
Labels: size/L
