Repository FromDoppler/doppler-webapp, pull requests merged in 2024-08, with the labels that each got.

#2507 [DOI-1539] Remove cancel invitation option when invitation is already canceled
  src/components/ControlPanel/CollaboratorsSections/index.js
Labels: size/S

#2508 [DOI-1538] Redirect collaborators out of collaborator section
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/components/ControlPanel/CollaboratorsSections/index.test.js
Labels: size/M

#2509 [DOI-1396] Add collaborator edition card in control panel
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#2510 [DAT-2115] - Set the current chat plan
  src/components/BuyProcess/PlanChat/index.js
  src/components/BuyProcess/PlanChat/index.test.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/hooks/useFetchConversationPlans/conversationPlansReducer/index.js
  src/hooks/useFetchConversationPlans/conversationPlansReducer/index.test.js
  src/hooks/useFetchConversationPlans/index.js
  src/hooks/useFetchConversationPlans/index.test.js
  src/services/doppler-legacy-client.test.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#2512 [DOI-1375] Add Collaborator edition section
  src/App.js
  src/components/ControlPanel/CollaboratorEditionSection/index.js
  src/components/ControlPanel/CollaboratorEditionSection/index.test.js
  src/components/form-helpers/form-helpers.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2513 [DAT-1697] - Integrate with stepper
  .env.development
  .env.int
  .env.production
  .env.qa
  src/App.js
  src/components/BuyProcess/BuyProcessLayout/index.js
  src/components/BuyProcess/PlanChat/index.js
  src/components/BuyProcess/PlanSelection/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
  src/components/BuyProcess/ShoppingCart/Promocode/index.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/Plans/Checkout/Checkout.js
  src/services/doppler-account-plans-api-client.ts
  src/services/doppler-legacy-client.ts
Labels: size/L

#2514 [No-Ticket] Set inactive chatplan in the qa environment
  .env.qa
Labels: size/XS

#2515 [DAT-2123] - Add translations for the English
  .env.development
  src/components/BuyProcess/BuyProcessLayout/index.js
  src/components/BuyProcess/Stepper/index.js
  src/components/BuyProcess/Stepper/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2516 [No-Task] - Fix issue
  src/components/BuyProcess/BuyProcessLayout/index.js
Labels: size/XS

#2517 [DOI-1545] Update colaborator information view
  src/components/ControlPanel/CollaboratorEditionSection/index.js
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/components/ControlPanel/CollaboratorsSections/index.test.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
  src/services/doppler-user-api-client.double.ts
  src/services/doppler-user-api-client.test.ts
  src/services/doppler-user-api-client.ts
Labels: size/L

#2518 [DOI-1547] Add missing login rejection status
  src/components/ControlPanel/CollaboratorEditionSection/index.js
  src/components/Login/Login.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
Labels: size/M

#2519 [DAT-2136] - Fix issue with the stepper
  src/App.js
  src/components/BuyProcess/BuyProcessLayout/index.js
  src/components/BuyProcess/LandingPacksSelection/index.js
  src/components/BuyProcess/PlanChat/index.js
  src/components/BuyProcess/PlanTypes/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/LandingPackCheckoutButton.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/LandingPackCheckoutLink.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/LandingPackCheckoutLink.test.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2520 [DOI-1552] Avoid form rendering when user already accepted collaborator invite
  src/components/CollaborationInvite/index.js
  src/components/CollaborationInvite/index.test.js
Labels: size/S

#2521 [DOI-1558] Conversations promotional page
  .env.development
  .env.int
  .env.production
  .env.qa
  src/App.js
  src/components/Conversations/google-data-studio.gif
  src/components/Conversations/index.js
  src/components/Conversations/index.test.js
  src/components/Conversations/logo.svg
  src/components/Conversations/screenShot.png
  src/components/shared/Promotional/Promotional.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.doubles.ts
  src/services/doppler-legacy-client.ts
Labels: size/L

#2522 [DAT-2140] - send total buy conversation plan
  src/components/BuyProcess/PlanChat/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
Labels: size/S

#2523 [DOI-1558] Modify endpoint name
  src/services/doppler-legacy-client.ts
Labels: size/XS

#2524 [DOI-1558] Add button spinner for promotional pages
  src/components/shared/Promotional/Promotional.js
Labels: size/S

#2525 [DOI-1558] Send func as parameter
  src/components/shared/Promotional/Promotional.js
Labels: size/XS

#2526 [No-Task] Set in true to buy conversation plan in qa
  .env.qa
  src/services/doppler-legacy-client.ts
Labels: size/XS

#2528 [DOI-1551] Add invite status expired and fix translation
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2529 [DOI-1571] Replace button text
  src/components/Conversations/google-data-studio.gif
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2530 [DAT-2151] - Include page for buy only chat plan
  src/App.js
  src/components/BuyProcess/PlanChat/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/Plans/BuyConversation/index.js
  src/components/Plans/BuyConversation/index.test.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
Labels: size/L

#2531 [No-ticket] Fix issue when show summary
  src/components/Plans/Checkout/Checkout.js
Labels: size/XS

#2532 [DAT-2151] - fix issue when redirect to the summary page
  src/components/BuyProcess/ShoppingCart/utils.js
Labels: size/XS

#2527 feat: format date to local date using useIntl
  src/components/ControlPanel/CollaboratorsSections/index.js
  src/services/doppler-legacy-client.test.js
  src/services/doppler-user-api-client.double.ts
Labels: size/M
