Repository FromDoppler/doppler-webapp, pull requests merged in 2024-01, with the labels that each got.

#2439 chore: remove christmas logo
  src/components/ForgotPassword/ForgotPassword.js
  src/components/Login/Login.js
  src/components/Signup/Signup.js
  src/components/shared/Promotions/Promotions.js
Labels: size/S

#2440 [DAT-1846] Update message content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2442 [DAT-1847] - Update content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2443 [DOI-1174] Change dkim section name
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2430 Dat 1633 plan selection screen
  .prettierrc
  src/App.js
  src/components/BuyProcess/NavigationTabs/index.js
  src/components/BuyProcess/NavigationTabs/index.test.js
  src/components/BuyProcess/PaymentFrequency/SubscriptionType/index.js
  src/components/BuyProcess/PaymentFrequency/index.js
  src/components/BuyProcess/PlanSelection/BannerUpgrade/index.js
  src/components/BuyProcess/PlanSelection/GoBackButton/index.js
  src/components/BuyProcess/PlanSelection/SubscriptionType/index.js
  src/components/BuyProcess/PlanSelection/SubscriptionType/index.test.js
  src/components/BuyProcess/PlanSelection/index.js
  src/components/BuyProcess/PlanSelection/index.test.js
  src/components/BuyProcess/PlanSelection/reducers/planTypesReducer.js
  src/components/BuyProcess/PlanSelection/reducers/planTypesReducer.test.js
  src/components/BuyProcess/PlanSelection/reducers/plansByTypeReducer.js
  src/components/BuyProcess/PlanSelection/reducers/plansByTypeReducer.test.js
  src/components/BuyProcess/RadioBox/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.test.js
  src/components/BuyProcess/ShoppingCart/CheckoutLink/index.js
  src/components/BuyProcess/ShoppingCart/ItemCart/index.js
  src/components/BuyProcess/ShoppingCart/NextInvoices/index.js
  src/components/BuyProcess/ShoppingCart/Promocode/PromocodeMessages/index.js
  src/components/BuyProcess/ShoppingCart/Promocode/index.js
  src/components/BuyProcess/ShoppingCart/Promocode/reducers/promocodeReducer.js
  src/components/BuyProcess/ShoppingCart/Promocode/reducers/promocodeReducer.test.js
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/components/BuyProcess/Slider/index.js
  src/components/BuyProcess/UnexpectedError/index.js
  src/components/BuyProcess/UnexpectedError/index.styles.js
  src/components/BuyProcess/UnexpectedError/index.test.js
  src/components/Login/Login.js
  src/components/Login/LoginErrorAccountNotValidated.js
  src/components/Plans/Checkout/Checkout.js
  src/components/Plans/Checkout/Checkout.test.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryButton/index.test.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummaryTitle/index.test.js
  src/components/Plans/Checkout/CheckoutSummary/MercadoPagoInformation/index.js
  src/components/Plans/Checkout/CheckoutSummary/TransferInformation/index.js
  src/components/Plans/Checkout/Discounts/Discounts.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.test.js
  src/components/Plans/Checkout/PurchaseSummary/PurchaseSummary.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-legacy-client.ts
  src/services/planService/index.ts
  src/utils.ts
Labels: size/XXL

#2444 [No ticket] Withelist conversations url for qa
  src/utils.ts
Labels: size/XS

#2445 revert: withelist conversations url for qa
  src/utils.ts
Labels: size/XS

#2447 fix: adjust next invoice date
  src/components/BuyProcess/ShoppingCart/NextInvoices/index.js
Labels: size/XS

#2446 feat: create stepper component
  src/components/BuyProcess/Stepper/index.js
  src/components/BuyProcess/Stepper/index.test.js
Labels: size/M

#2448 feat: add discount for admin
  src/components/BuyProcess/ShoppingCart/index.js
  src/components/BuyProcess/ShoppingCart/utils.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2438 Dat 1841 add finger printing
  package.json
  src/components/Login/Login.js
  src/hooks/useFingerPrinting/index.js
  src/services/doppler-legacy-client.ts
  yarn.lock
Labels: size/S

#2449 DAT-1747 Prevent CC and MERCADO PAGO payment method form fields from resetting
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
  src/components/Plans/Checkout/PaymentMethod/MercadoPagoArgentina/index.js
Labels: size/M
