Repository FromDoppler/doppler-webapp, pull requests merged in 2025-03, with the labels that each got.

#2609 [DAT-2391] - Add basic my-plan page
  src/App.js
  src/components/MyPlan/index.js
  src/components/MyPlan/index.test.js
Labels: size/M

#2611 [DAT-2398]
  src/components/Dashboard/LearnWithDoppler/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2610 [DAT-2325]
  src/components/SiteTrackingRequired/SiteTrackingRequired.js
Labels: size/S

#2612 [DAT-2395] - Add tabs component in the my-plan page
  src/components/MyPlan/AddOns/index.js
  src/components/MyPlan/BillingHistory/index.js
  src/components/MyPlan/Header/index.js
  src/components/MyPlan/PaymentMethod/index.js
  src/components/MyPlan/SubscriptionDetails/index.js
  src/components/MyPlan/Tabs/index.js
  src/components/MyPlan/index.js
Labels: size/L

#2613 [DAT-2403] add params to the dashboard card
  src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js
  src/components/Dashboard/LearnWithDoppler/index.js
Labels: size/M

#2614 [DAT-2396] - Add subscriptiodetails component in the my plan page
  src/components/MyPlan/GrayCard/index.js
  src/components/MyPlan/Header/index.js
  src/components/MyPlan/SubscriptionDetails/Features/index.js
  src/components/MyPlan/SubscriptionDetails/index.js
  src/components/MyPlan/index.js
  src/components/MyPlan/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2616 [DAT-2382] - fix issue with promocode
  src/components/BuyProcess/ShoppingCart/Promocode/index.js
Labels: size/XS

#2617 [DAT-2444] - Hide first steps section in the dashboard page
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.test.js
Labels: size/L

#2618 [DAT-2445]
  src/components/BuyProcess/ShoppingCart/CheckoutButton/index.js
Labels: size/XS

#2619 [DAT-2435] - Add push notifiactions promotional page
  .env.development
  .env.int
  .env.production
  .env.qa
  src/App.js
  src/components/NewFeatures/NewFeatures.js
  src/components/PushNotifications/index.js
  src/components/PushNotifications/index.test.js
  src/components/PushNotifications/logo.svg
  src/components/PushNotifications/push-configuration--en.png
  src/components/PushNotifications/push-configuration--es.png
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
  src/services/doppler-legacy-client.ts
Labels: size/L

#2621 [DAT-2452] - Show first steps in the dashboard page
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.test.js
Labels: size/L

#2622 [DOW-83] Move wordpress box to native integrations
  src/i18n/en.js
  src/i18n/es.js
  src/services/control-panel-service.ts
Labels: size/S

#2623 [DAT-2448] - Integrate with the activate ednpoint
  src/services/doppler-billing-user-api-client.ts
Labels: size/S
