Repository FromDoppler/doppler-webapp, pull requests merged in 2025-08, with the labels that each got.

#2681 [DAT-2306] - Add form to start the flow of cancellation account
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/MyPlan/CancellationAccount/CancellationWithoutRetentionModal/index.js
  src/components/MyPlan/CancellationAccount/Modal/Form/index.js
  src/components/MyPlan/CancellationAccount/Modal/Form/styles.js
  src/components/MyPlan/CancellationAccount/Modal/index.js
  src/components/MyPlan/CancellationAccount/index.js
  src/components/MyPlan/SubscriptionDetails/EmailMarketingPlan/index.js
  src/components/MyPlan/SubscriptionDetails/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2683 [no-task] Remove mastercard credit card
  src/components/Plans/Checkout/PaymentMethod/CreditCard.js
  src/i18n/en.js
  src/i18n/es.js
  src/img/credit-cards.png
Labels: size/S

#2682 Esconder box de big box si no tiene el feature activo
  src/services/control-panel-service.ts
  src/services/doppler-legacy-client.ts
Labels: size/XS

#2685 [no-task] - Update content for the button
  src/i18n/es.js
Labels: size/XS

#2687 [DAT-2572] - Add cancellation without retention modal
  src/components/MyPlan/CancellationAccount/CancellationWithoutRetentionModal/index.js
  src/components/MyPlan/CancellationAccount/Modal/Form/index.js
  src/components/MyPlan/CancellationAccount/Modal/index.js
  src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.js
  src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/styles.js
  src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.js
  src/components/MyPlan/CancellationAccount/index.js
  src/components/MyPlan/SubscriptionDetails/AddOnPlan/ConversationPlan/index.js
  src/components/MyPlan/SubscriptionDetails/AddOnPlan/OnSitePlan/index.js
  src/components/MyPlan/SubscriptionDetails/AddOnPlan/PushNotificationPlan/index.js
  src/components/MyPlan/SubscriptionDetails/EmailMarketingPlan/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/XL

#2688 [no-task] - Add success cancellation account modal
  src/components/MyPlan/CancellationAccount/Modals/SuccessAccountCancellation/index.js
  src/components/MyPlan/CancellationAccount/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2689 [DAT-2572] - Add success cancellation account modal
  src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2692 [no-task] - Add loading in the button
  src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.js
  src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.js
Labels: size/L

#2693 [no-task] - Update title modal
  src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.js
  src/components/MyPlan/CancellationAccount/Modals/SuccessAccountCancellation/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2696 [no-task] - Set in trhe show cancellation button for free user
  .env.production
Labels: size/XS

#2702 [no-task] - Update logic when set the schedule cancellation request
  src/components/MyPlan/CancellationAccount/Modals/CancellationWithoutRetention/index.test.js
  src/components/MyPlan/CancellationAccount/Modals/ConsultingOffer/index.js
  src/components/MyPlan/CancellationAccount/Modals/ConsultingOffer/index.test.js
  src/components/MyPlan/CancellationAccount/Modals/SuccessAccountCancellation/index.test.js
  src/components/MyPlan/CancellationAccount/Modals/SuccessScheduledCancellation/index.test.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M

#2703 [DAT-2633] - Send consulting offer notification to the customer experience
  src/components/MyPlan/CancellationAccount/Modals/ConsultingOffer/index.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.test.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/M
