Repository FromDoppler/doppler-webapp, pull requests merged in 2025-02, with the labels that each got.

#2596 [DAT-2356] - Update content of the error about invalid credit card
  src/components/Plans/Checkout/PaymentMethod/PaymentMethod.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2598 DAT-2365
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2600 [DAT-2369] - Change logic to redirect url in the onsite page
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/OnSite/index.js
  src/components/OnSite/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2601 [no-task] - Remove target blank for the app url
  src/components/Dashboard/LearnWithDoppler/TextPreviewPost/TextPreviewPost.js
  src/components/Dashboard/LearnWithDoppler/index.js
Labels: size/XS

#2604 Dat 2329
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  src/components/MenuDemo/MenuDemo.js
Labels: size/XS

#2605 [DAT-2366] - Add class for the item in the Promotional page
  src/components/OnSite/index.js
  src/components/shared/Promotional/Promotional.js
Labels: size/XS

#2606 [DAT-2280]
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
Labels: size/M
