Repository FromDoppler/doppler-webapp, pull requests merged in 2025-04, with the labels that each got.

#2620 [DAT-2450] Update zendesk script
  public/index.html
Labels: size/XS

#2625 [DAT-2432] - Update checkout summary to supports push notifications
  src/components/Plans/Checkout/CheckoutSummary/AddOnPlanInformation/index.js
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/components/Plans/Checkout/CheckoutSummary/OnSitePlanInformation/index.js
  src/components/Plans/Checkout/Reducers/checkoutSummaryReducer.js
  src/hooks/useFetchAddOnPlans/index.js
  src/i18n/en.js
  src/i18n/es.js
  src/services/doppler-billing-user-api-client.double.ts
  src/services/doppler-billing-user-api-client.ts
Labels: size/L

#2626 [DAT-2423] - Add push notification slide in the carrousel
  public/images/addons-carousel-slide-4--en.png
  public/images/addons-carousel-slide-4--es.png
  src/components/Plans/Checkout/CheckoutSummary/CheckoutSummary.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2627 Update card about EMMS is about to begin
  src/i18n/es.js
Labels: size/XS

#2629 fix issue with english
  src/i18n/en.js
Labels: size/XS

#2630 [DAT-2470] - Update card for the emms in progress
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2631 [DAT-2471] - Update EMMS card when the event is ended
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#2632 [DAT-2447] - Update content for the push notifications
  public/images/addons-carousel-slide-4--en.png
  public/images/addons-carousel-slide-4--es.png
  src/components/BuyProcess/PushNotificationPlanSelection/index.js
  src/components/PushNotifications/push-configuration--en.png
  src/components/PushNotifications/push-configuration--es.png
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2633 [DAT-2476] - Update url to redirect after acitvate push
  src/components/PushNotifications/index.js
  src/components/PushNotifications/index.test.js
Labels: size/S

#2634 [DAT-2477] - Update images for the carrousel and promotional page
  public/images/addons-carousel-slide-4--en.png
  public/images/addons-carousel-slide-4--es.png
  src/components/PushNotifications/push-configuration--en.png
  src/components/PushNotifications/push-configuration--es.png
Labels: size/XS
