Repository FromDoppler/doppler-webapp, pull requests merged in 2025-09, with the labels that each got.

#2698 DOP-1844 - Push notification panel section
  src/App.js
  src/components/ControlPanel/PushNotificationSection/PlanAlert/planAlert.jsx
  src/components/ControlPanel/PushNotificationSection/helper/PushSwitch.jsx
  src/components/ControlPanel/PushNotificationSection/index.js
  src/components/ControlPanel/PushNotificationSection/index.test.js
  src/components/styles/messages.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2707 [DAT-2638] - Update flow for the users with contacts plan or monthly
  src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.js
  src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.test.js
  src/components/MyPlan/CancellationAccount/index.js
  src/doppler-types.ts
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2709 [DAT-2611] - Set in true show Unsubscribe button in Production environment
  .env.production
  src/i18n/es.js
Labels: size/XS

#2708 Agregar action button rfm
  src/components/Integrations/Shopify/Shopify.js
Labels: size/S

#2714 [DAT-2655] - Run prettier in the webapp
  src/components/ControlPanel/PushNotificationSection/index.js
  src/components/ControlPanel/PushNotificationSection/index.test.js
  src/components/Integrations/Shopify/Shopify.js
  src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.js
  src/components/MyPlan/CancellationAccount/Modals/AccountCancellationRequest/index.test.js
  src/components/styles/messages.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/L

#2718 RFM loading show spinner
  src/components/Integrations/Shopify/Shopify.js
Labels: size/S

#2724 DOP-1881 - update content for push notification
  src/components/ControlPanel/PushNotificationSection/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#2727 [DOI-2341] Remove redirection to dashboard for cms in promotional pages
  src/components/Conversations/index.js
  src/components/Conversations/index.test.js
  src/components/OnSite/index.js
  src/components/OnSite/index.test.js
Labels: size/M

#2729 [DAT-2676] Update Mi Plan content
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#2730 DOP-1887 - update push notification content
  src/components/ControlPanel/PushNotificationSection/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S
